### PR TITLE
fix: include query params in HTTP getter cache key

### LINKED ISSUE #2103: go-getter cache key conflict for HttpGetter
### Operating system

Any

### Helmfile Version

v1.1.1-v1.1.3

### Helm Version

v3.18.4

### Bug description

We use remote values files from GitLab. To speed up the templating process, we use direct links to the files instead of git: https://gitlab.my.company/api/v4/projects/test/repository/files/helm%2Falerts%2Ftemplates%2Fbackend.yaml/raw?ref=29b5609c7c77c03e9b7752fa5a518f242b598c21.

We build different environments simultaneously and use URLs with different ref parameters for each of them.

However, the cache key for these links does not include query parameters:
```
remote> cached dir: /Users/user/Library/Caches/helmfile/https_gitlab_my_company/api/v4/projects/test/repository/files/helm/alerts/templates/backend.yaml
```

As a result, we get the wrong version of the file.

It seems the best way to fix it would be to include query parameters in the cache key.

### Example helmfile.yaml

```yaml
releases:
  - name: test-dev
    namespace: dev
    chart: "../../../helm/test"
    values:
      - https://gitlab.my.company/api/v4/projects/test/repository/files/helm%2Falerts%2Ftemplates%2Fbackend.yaml/raw?ref=29b5609c7c77c03e9b7752fa5a518f242b598c21
  - name: test-prod
    namespace: prod
    chart: "../../../helm/test"
    values:
      - https://gitlab.my.company/api/v4/projects/test/repository/files/helm%2Falerts%2Ftemplates%2Fbackend.yaml/raw?ref=d80839cf37d860c8aa9a0503fe463278f26cd5e2
```

### Error message you've seen (if any)

```
remote> cached dir: /Users/user/Library/Caches/helmfile/https_gitlab_my_company/api/v4/projects/test/repository/files/helm/alerts/templates/backend.yaml
```

### Steps to reproduce

-

### Working Helmfile Version

-

### Relevant discussion

_No response_

### PR DESCRIPTION
**Pull request by aditmeno**
## Summary

Fixes #2103

When helmfile caches remote HTTP files fetched via the "normal" getter (plain `https://` URLs without a `git::` prefix), the cache key **did not include query parameters**. This caused URLs that differ only in query params (e.g. `?ref=commit1` vs `?ref=commit2`) to share the same cache directory, silently returning the wrong file version.

**Scenario from the issue:** Two GitLab raw file URLs pointing to different commits produce the same cache path:
```
https://gitlab.example.com/api/v4/.../backend.yaml/raw?ref=29b5609  → same cache
https://gitlab.example.com/api/v4/.../backend.yaml/raw?ref=d80839c  → same cache
```

## Root Cause

In `pkg/remote/remote.go`, the `Fetch()` method correctly computes `cacheKey` including query parameters on [lines 238–250](https://github.com/helmfile/helmfile/blob/2f8b9cbd/pkg/remote/remote.go#L238-L250). However, for `u.Getter == "normal"` (plain HTTP/HTTPS URLs), it **overwrites** `cacheKey` with only `scheme + host`, discarding query params entirely:

```go
// Before (bug):
if u.Getter == "normal" {
    srcDir = fmt.Sprintf("%s://%s", u.Scheme, u.Host)
    cacheKey = replacer.Replace(srcDir)        // ← query params lost
    cacheDirPath = filepath.Join(r.Home, cacheKey, u.Dir)
}
```

## Fix

Extract the query-params suffix into a `paramsSuffix` variable computed once, then reuse it in both the default and "normal" getter cache key paths:

```go
// After (fix):
if u.Getter == "normal" {
    srcDir = fmt.Sprintf("%s://%s", u.Scheme, u.Host)
    normalDirKey := replacer.Replace(srcDir)
    if paramsSuffix != "" {
        cacheKey = fmt.Sprintf("%s.%s", normalDirKey, paramsSuffix)
    } else {
        cacheKey = normalDirKey
    }
    cacheDirPath = filepath.Join(r.Home, cacheKey, u.Dir)
}
```

**Before:** `https_gitlab_example_com/api/v4/.../backend.yaml` (same for all refs)
**After:** `https_gitlab_example_com.ref=29b5609/api/v4/.../backend.yaml` (unique per ref)

## Changes

| File | Change |
|------|--------|
| `pkg/remote/remote.go` | Extract `paramsSuffix` and apply it in the `"normal"` getter cache key path |
| `pkg/remote/remote_test.go` | Add `TestParse` case for HTTPS+query; add `TestRemote_HttpUrlWithQueryParams` (cache hit/miss); add `TestRemote_HttpUrlQueryParamsAvoidCacheCollision` |
| `test/integration/test-cases/issue-2103.sh` | Integration test: local HTTP server + helmfile template verifying different `?ref=` values produce different content |
| `test/integration/test-cases/issue-2103/input/` | Supporting files for the integration test (Go HTTP server, helmfile.yaml.gotmpl) |
| `test/integration/run.sh` | Register `issue-2103.sh` in integration suite |

## Test Plan

- [x] `go test ./pkg/remote/ -v -run "TestRemote_Http|TestParse"` — all new tests pass
- [x] `go test ./pkg/remote/` — full suite passes, no regressions on git/s3/ssh getter tests
- [ ] Integration test (`test/integration/test-cases/issue-2103.sh`) — spins up a Go HTTP server returning different YAML per `?ref=`, runs `helmfile template`, asserts both values appear in output

### CODE REVIEW

**Comment by yxxhero** [comment]
@aditmeno are all codes generated by ai?

**Comment by aditmeno** [comment]
> @aditmeno are all codes generated by ai?

These PRs, yeah

I normally use Claude Code to supervise issues

File: pkg/remote/remote.go [hunk 1]
```diff
@@ -235,16 +235,28 @@ func (r *Remote) Fetch(path string, cacheDirOpt ...string) (string, error) {
...
+	// so that sensitive credentials in query parameters are never written to disk or log output.
+	var paramsSuffix string
+	var redactedQuery neturl.Values
+	if len(query) > 0 {
+		redactedQuery = maps.Clone(query)
+		for key := range redactedQuery {
+			lk := strings.ToLower(key)
+			if lk == "sshkey" || lk == "token" || lk == "access_token" ||
+				lk == "private_token" || lk == "password" || lk == "secret" ||
+				lk == "signature" || lk == "sig" || strings.HasSuffix(lk, "_key") {
```
Comment (yxxhero) [inline pkg/remote/remote.go]: can we use strings.Contain

Comment (aditmeno) [reply pkg/remote/remote.go]: Good point, fixing

**Comment by aditmeno** [comment]
`cacheBaseDir` is defined at line 228 of `remote.go` and is in scope at line 289. This is a false positive — Copilot only sees the diff context, not the full file.

**Comment by aditmeno** [comment]
@yxxhero PR is ready for review

**Review by yxxhero — APPROVED** [review]
