### PR TITLE
fix: helmBinary setting ignored in multi-document YAML files

### LINKED ISSUE #2319: Ignoring the helmBinary setting in helmfile.yaml
### Operating system

unix

### Helmfile Version

1.2.2

### Helm Version

4.0.1

### Bug description

Ignoring the helmBinary setting in helmfile.yaml
This issue also applies to previous 0.* releases.

As a temporary workaround, in previous versions, I used the --helm-binary argument in the helmfile command: helmfile apply -n $NAMESPACE -e $ENVIRONMENT_NAME -l app=$CHART --set ${APP_TAG_PATH}=$VERSION --helm-binary=werf $HELMFILE_EXTRA_ARGS

With the transition to 1.*, it is no longer possible to pass arguments, and it turns out that there is no longer a temporary solution

The werf binary file is additionally embedded into the helmfile image itself and copied to the path /usr/bin/werf. The file is made executable.

### Example helmfile.yaml
```
helmBinary: "/usr/bin/werf"

helmDefaults:
  createNamespace: true
  atomic: true
  wait: true
  timeout: 300
  #recreatePods: true

repositories:
  - name: iov
    url: https://sregistry/chartrepo/iov-application
    username: {{ env "IOV_USERNAME" | default "" }}
    password: {{ env "IOV_PASSWORD" | default "" }}

environments:
  dev:
    values:
      - apps:
        - auth-service-cc

---

bases:
{{- range .Values.apps }}
  - releases/{{ . }}.yaml
{{- end }}

```
### Error message you've seen (if any)

There are no errors, it's just that the function for which werf is used - kubedog - isn't working.

### Steps to reproduce

perform installation

### Working Helmfile Version

-

### Relevant discussion

_No response_

### PR DESCRIPTION
**Pull request by yxxhero**
## Summary

Fixes #2319 - The `helmBinary` and `kustomizeBinary` settings in `helmfile.yaml` were being ignored when using multi-document YAML files (files with `---` separators).

## Root Cause

When processing multi-document YAML files, the `load()` function splits the file into parts and processes each part separately. Each part was calling `applyDefaultsAndOverrides()` which would set an empty `helmBinary`/`kustomizeBinary` to the default value (`"helm"` or `"kustomize"`). When merging parts with `mergo.WithOverride`, the default value from a later part would override the correct value from an earlier part.

For example, with this helmfile.yaml:
```yaml
helmBinary: "/usr/bin/werf"

---

bases:
  - ./base.yaml
```

The first part correctly sets `helmBinary: "/usr/bin/werf"`, but the second part has an empty `helmBinary` which gets defaulted to `"helm"`, and then overrides the correct value during merge.

## Fix

- Added a new `applyDefaults` parameter to `ParseAndLoad()` in `pkg/state/create.go` to control when defaults are applied
- Modified `rawLoad()` in `pkg/app/desired_state_file_loader.go` to pass `applyDefaults=false` when processing individual parts
- Added a call to `ApplyDefaultsAndOverrides()` after all parts are merged in `load()` to apply defaults once on the final merged state
- Exported `ApplyDefaultsAndOverrides()` method for use by the app package

## Testing

- All existing unit tests pass (`pkg/state/...`, `pkg/app/...`)
- Added `TestHelmBinaryInMultiDocumentYAML` - unit test at ParseAndLoad level
- Added `TestHelmBinaryPreservedInMultiDocumentYAML` - integration test at loadDesiredStateFromYaml level
- Manually tested with a multi-document helmfile.yaml containing `helmBinary` setting

### CODE REVIEW

File: pkg/app/desired_state_file_loader.go [hunk 1]
```diff
@@ -297,6 +298,14 @@ func (ld *desiredStateLoader) load(env, overrodeEnv *environment.Environment, ba
 		}
 	}
 
+	// After all parts are merged, apply defaults and overrides to ensure
+	// that values from earlier parts (like helmBinary) are preserved correctly
+	// in the merged state.
+	// See https://github.com/helmfile/helmfile/issues/2319
+	if evaluateBases {
+		ld.underlying().ApplyDefaultsAndOverrides(finalState)
+	}
```
Comment (aditmeno) [inline pkg/app/desired_state_file_loader.go:307]: **Missing regression test.** This is the core of the fix — deferring defaults until after all parts are merged — but there's no test exercising this path.

Please add a unit test that:
1. Loads a multi-document YAML where document 1 sets `helmBinary: "/usr/bin/werf"` and document 2 does not set `helmBinary`
2. Asserts the merged state preserves `"/usr/bin/werf"` instead of falling back to `"helm"`

Without this, the bug from #2319 could silently regress in future refactors. Testing at the `ParseAndLoad` level alone isn't sufficient since the bug is in how `load()` orchestrates multiple `rawLoad()` calls + post-merge default application.

File: pkg/app/desired_state_file_loader.go [hunk 2]
```diff
@@ -177,15 +177,15 @@ func (a *desiredStateLoader) underlying() *state.StateCreator {
 	return c
 }
 
-func (a *desiredStateLoader) rawLoad(yaml []byte, baseDir, file string, evaluateBases bool, env, overrodeEnv *environment.Environment) (*state.HelmState, error) {
+func (a *desiredStateLoader) rawLoad(yaml []byte, baseDir, file string, evaluateBases bool, applyDefaults bool, env, overrodeEnv *environment.Environment) (*state.HelmState, error) {
```
Comment (aditmeno) [inline pkg/app/desired_state_file_loader.go]: Nit: `applyDefaults` is always `false` at the only call site (line 248). Consider removing the parameter and hardcoding `false` in the `ParseAndLoad` call inside `rawLoad` to keep the API surface smaller.

File: pkg/state/create.go [hunk 3]
```diff
@@ -137,6 +137,12 @@ func (c *StateCreator) Parse(content []byte, baseDir, file string) (*HelmState,
 	return &state, nil
 }
 
+// ApplyDefaultsAndOverrides applies default binary paths and command-line overrides.
+// This is an exported version of applyDefaultsAndOverrides for use by the app package.
+func (c *StateCreator) ApplyDefaultsAndOverrides(state *HelmState) {
```
Comment (aditmeno) [inline pkg/state/create.go:142]: Nit: `applyDefaultsAndOverrides` also sets `DefaultKustomizeBinary`. The fix correctly addresses both, but the PR title/description only mentions `helmBinary`. Worth updating the description to note `kustomizeBinary` is also fixed by this change.

**Comment by yxxhero** [comment]
@aditmeno all is ok.
