### PR TITLE
fix: ensure plain http is supported across all helmfile commands

### LINKED ISSUE #1857: Helmfile should respect the planHttp option and modify its commands to helm accordingly
### Operating system

Amazon Linux 2

### Helmfile Version

v0.169.2

### Helm Version

v3.16.3

### Bug description

Setting the `plainHttp` within a `helmfile.yaml` is ignored and not respected. This is evident when it is added to both a `release` and a `repository`. This flag is essential as Helm provides native HTTP support for local OCI repositories.To demonstrate the problem:

1. Spin up a local registry:
   ```sh
   docker run -d -p 5000:5000 --restart always --name registry registry:2
   ```

1. Pull an existing chart and publish it into your local OCI registry for use by helmfile:
   ```sh
   helm pull oci://registry-1.docker.io/bitnamicharts/postgresql
   helm push --plain-http postgresql-16.3.5.tgz oci://localhost:5000/charts
   ```

1. Create the following `helmfile.yaml`:
   ```yaml
   releases:
     - name: postgresql
       namespace: default
       chart: oci://registry:5000/charts/postgresql
       version: "*"
       plainHttp: true
   ```

1. Create a Kubernetes cluster using `k3d` or any other tool that you prefer, and sync the helmfile:
   ```sh
   k3d cluster create demo
   helmfile apply
   ```

### Example helmfile.yaml

```yaml
releases:
- name: postgresql
  namespace: default
  chart: oci://registry:5000/charts/postgresql
  version: "*"
  plainHttp: true
```

### Error message you've seen (if any)

```sh
Pulling localhost:5000/charts/postgresql:*
in ./helmfile.yaml: [release "postgresql": command "/nix/store/fkn0vawlzw4cyih8y3036ydm6rxdif2j-helm-3.16.4/bin/helm" exited with non-zero status:

PATH:
  /nix/store/fkn0vawlzw4cyih8y3036ydm6rxdif2j-helm-3.16.4/bin/helm

ARGS:
  0: helm (4 bytes)
  1: pull (4 bytes)
  2: oci://localhost:5000/charts/postgresql (37 bytes)
  3: --version (9 bytes)
  4: * (1 bytes)
  5: --destination (13 bytes)
  6: /tmp/nix-shell.8u86qt/helmfile2694484463/default/postgresql/postgresql/_ (72 bytes)
  7: --untar (7 bytes)

ERROR:
  exit status 1

EXIT STATUS
  1

STDERR:
  Error: Get "https://localhost:5000/v2/charts/postgresql/tags/list": http: server gave HTTP response to HTTPS client

COMBINED OUTPUT:
  Error: Get "https://localhost:5000/v2/charts/postgresql/tags/list": http: server gave HTTP response to HTTPS client]
```

### Steps to reproduce

Steps above

### Working Helmfile Version

N/A

### Relevant discussion

https://github.com/helmfile/helmfile/discussions/1364

### PR DESCRIPTION
**Pull request by purpleclay**
closes #1857 

This pull request includes several refactorings and improvements to the `HelmState` methods in the `pkg/state/state.go` file. The changes focus on simplifying the code and improving the handling of flags for Helm commands.

Refactorings and improvements:

* [`pkg/state/state.go`](diffhunk://#diff-7e4e87a1e777423a3d9a915e00fb78a9c4fc2f4c476863f60b67e89b9c635697L2667-R2706): Refactored the `appendChartDownloadFlags` method to use new helper methods `needsPlainHttp` and `needsInsecureSkipTLSVerify`, which encapsulate the logic for determining whether certain flags are needed.
* [`pkg/state/state.go`](diffhunk://#diff-7e4e87a1e777423a3d9a915e00fb78a9c4fc2f4c476863f60b67e89b9c635697L2847-R2881): Updated the `flagsForDiff` method to remove the `--plain-http` flag if it is present, as `helm diff` does not support this flag.
* [`pkg/state/state.go`](diffhunk://#diff-7e4e87a1e777423a3d9a915e00fb78a9c4fc2f4c476863f60b67e89b9c635697L3846-R3878): Modified the `getOCIChart` method to include the `appendChartDownloadFlags` call, ensuring that the necessary flags are appended when pulling an OCI chart.

### CODE REVIEW

File: pkg/state/state.go [hunk 1]
```diff
@@ -2844,11 +2844,11 @@ func (st *HelmState) flagsForDiff(helm helmexec.Interface, release *ReleaseSpec,
 	// `helm template --validate` and `helm upgrade --dry-run` ignore `--kube-version` flag.
 	// For the moment, not specifying kubeVersion.
 	flags = st.appendApiVersionsFlags(flags, release, "")
-
 	flags = st.appendConnectionFlags(flags, release)
-
 	flags = st.appendChartDownloadFlags(flags, release)
 
+	// TODO: ensure the --plain-http flag is stripped before sending command to helm-diff
+
```
Comment (purpleclay) [inline pkg/state/state.go:2851]: I haven't implemented the fix here yet. I wanted to get feedback first. The issue here is that `--plain-http` is being added to the list of flags through the `st.appendChartDownloadFlags` function. To ensure `helm-diff` works as expected, this flag needs to be removed.

I could easily sanitise the slice and remove the flag if it exists?

File: flake.nix
Comment (purpleclay) [inline flake.nix:1]: Removing this file!

File: pkg/state/state.go (hunk 1 above)
Comment (yxxhero) [reply pkg/state/state.go:2851]: @purpleclay yeah. you can. let's review your changes.

Comment (purpleclay) [reply pkg/state/state.go]: I have pushed my latest changes. Looking forward to your feedback

Comment (purpleclay) [reply pkg/state/state.go]: I have manually tested this against all scenarios documented in the issue:

1. `--plain-http` is now correctly passed to `helm pull` when using a release and setting `plainHttp` to true.
2. `helmfile apply` correctly ignores the `--plain-http` flag when calling helm-diff.

**Comment by yxxhero** [comment]
@purpleclay cool. could you add some unittest?

File: pkg/state/state.go [hunk 2]
```diff
@@ -2664,26 +2664,46 @@ func (st *HelmState) kubeConnectionFlags(release *ReleaseSpec) []string {
...
 
-	if release.InsecureSkipTLSVerify || st.HelmDefaults.InsecureSkipTLSVerify || repoSkipTLSVerify {
+	if st.needsInsecureSkipTLSVerify(release, repo) {
 		flags = append(flags, "--insecure-skip-tls-verify")
 	}
 
 	return flags
 }
 
+func (st *HelmState) needsPlainHttp(release *ReleaseSpec, repo *RepositorySpec) bool {
```
Comment (yxxhero) [inline pkg/state/state.go:2681]: add tests.

File: pkg/state/state.go [hunk 3]
```diff
@@ -2664,26 +2664,46 @@ func (st *HelmState) kubeConnectionFlags(release *ReleaseSpec) []string {
...
+	}
+
+	if release != nil {
+		relPlainHttp = release.PlainHttp
+	}
+
+	return relPlainHttp || st.HelmDefaults.PlainHttp || repoPlainHttp
+}
+
+func (st *HelmState) needsInsecureSkipTLSVerify(release *ReleaseSpec, repo *RepositorySpec) bool {
```
Comment (yxxhero) [inline pkg/state/state.go:2694]: add tests.

File: pkg/state/state.go [hunk 4]
```diff
@@ -2844,11 +2864,21 @@ func (st *HelmState) flagsForDiff(helm helmexec.Interface, release *ReleaseSpec,
 	// `helm template --validate` and `helm upgrade --dry-run` ignore `--kube-version` flag.
 	// For the moment, not specifying kubeVersion.
 	flags = st.appendApiVersionsFlags(flags, release, "")
-
 	flags = st.appendConnectionFlags(flags, release)
-
 	flags = st.appendChartDownloadFlags(flags, release)
 
+	// `helm diff` does not support the `--plain-http` flag, this needs to be removed
+	repo, _ := st.GetRepositoryAndNameFromChartName(release.Chart)
```
Comment (yxxhero) [inline pkg/state/state.go:2871]: add tests

File: pkg/state/state.go (hunk 2 above)
Comment (purpleclay) [reply pkg/state/state.go:2681]: Done

File: pkg/state/state.go (hunk 3 above)
Comment (purpleclay) [reply pkg/state/state.go:2694]: Done

File: pkg/state/state.go (hunk 4 above)
Comment (purpleclay) [reply pkg/state/state.go:2871]: Done

**Comment by yxxhero** [comment]
@purpleclay cool. great.

**Review by yxxhero — APPROVED** [review]
