### PR TITLE
fix: ensure development versions of charts can be used across helmfile commands

### LINKED ISSUE #1864: Helmfile does not correctly handle development versions of charts
### Operating system

macOS 15.1 (Sequoia)

### Helmfile Version

v0.169.2

### Helm Version

v3.16.4

### Bug description

Helm supports publishing and pulling development releases (i.e. prerelease versions) of charts. Looking through the helmfile documentation, its config also states support through the `devel` option, which ultimately maps to the `--devel` flag to both the `helm` and `helm-diff` CLIs.

The only caveat to using the `--devel` flag is that a version should not be provided using the `--version` flag. If one is provided, it takes precedence.

`helmfile` is ignoring the presence of the `devel` option within the `getOCIQualifiedChartName` method in `state.go`.

To replicate this behaviour:

1. Spin up a local registry:
   ```sh
   docker run -d -p 5000:5000 --restart always --name registry registry:2
   ```

1. Pull an existing chart and publish it into your local OCI registry for use by helmfile:
   ```sh
   helm pull oci://ghcr.io/stefanprodan/charts/podinfo
   helm push --plain-http podinfo-6.7.1.tgz oci://localhost:5000/charts --version 6.7.1-1736671323
   ```

1. Create the following `helmfile.yaml`:
   ```yaml
   repositories:
      - name: charts
        url: localhost:5000/charts
        oci: true
        plainHttp: true

   releases:
     - name: podinfo
       namespace: default
       chart: charts/podinfo
       devel: true
   ```

1. Create a Kubernetes cluster using `k3d` or any other tool that you prefer, and sync the helmfile:
   ```sh
   k3d cluster create demo
   helmfile apply
   ```

### Example helmfile.yaml

```yaml
repositories:
  - name: charts
    url: localhost:5000/charts
    oci: true
    plainHttp: true

releases:
  - name: podinfo
    namespace: default
    chart: charts/podinfo
    devel: true
```

### Error message you've seen (if any)

```sh
$ helmfile sync
in ./helmfile.yaml: [release "podinfo": the version for OCI charts should be semver compliant, the latest tag is not supported anymore for helm >= 3.8.0]
```

### Steps to reproduce

See steps within bug description

### Working Helmfile Version

N/A

### Relevant discussion

_No response_

### PR DESCRIPTION
**Pull request by purpleclay**
closes #1864

This pull request includes refactorings to ensure the `--devel` flag is correctly passed into the required `helm` and `helm diff` commands.

- [`pkg/helmexec/exec.go`](https://github.com/helmfile/helmfile/pull/1865/files#diff-cc23d827ce15a3ce002578cc0b18d846fd3614d59ac080c703bdd17881466795R522): No longer set the version from the chart name and allow it to be passed through as part of the additional flags. This ensures `--version` and `--devel` are never included together. If you read the helm CLI docs, `--version` disables the behaviour of `--devel`.

### CODE REVIEW

File: pkg/helmexec/exec.go [hunk 1]
```diff
@@ -519,8 +519,8 @@ func (helm *execer) ChartPull(chart string, path string, flags ...string) error
 	if helmVersionConstraint.Check(helm.version) {
 		// in the 3.7.0 version, the chart pull has been replaced with helm pull
 		// https://github.com/helm/helm/releases/tag/v3.7.0
-		ociChartURL, ociChartTag := resolveOciChart(chart)
-		helmArgs = []string{"pull", ociChartURL, "--version", ociChartTag, "--destination", path, "--untar"}
+		ociChartURL, _ := resolveOciChart(chart)
+		helmArgs = []string{"pull", ociChartURL, "--destination", path, "--untar"}
```
Comment (purpleclay) [inline pkg/helmexec/exec.go:523]: No longer set the version from the chart name and allow it to be passed through as part of the additional flags. This ensures `--version` and `--devel` are never included together. If you read the helm CLI docs, `--version` disables the behaviour of `--devel`.

File: pkg/state/state.go [hunk 2]
```diff
@@ -2944,9 +2945,7 @@ func (st *HelmState) flagsForDiff(helm helmexec.Interface, release *ReleaseSpec,
 	return append(flags, common...), files, nil
 }
 
-func (st *HelmState) chartVersionFlags(release *ReleaseSpec) []string {
-	flags := []string{}
-
+func (st *HelmState) appendChartVersionFlags(flags []string, release *ReleaseSpec) []string {
```
Comment (purpleclay) [inline pkg/state/state.go:2948]: Follow the same convention used by other functions that append flags based on a certain condition

File: pkg/state/state.go [hunk 3]
```diff
@@ -3915,31 +3915,36 @@ func (st *HelmState) IsOCIChart(chart string) bool {
 	return repo.OCI
 }
 
-func (st *HelmState) getOCIQualifiedChartName(release *ReleaseSpec, helm helmexec.Interface) (qualifiedChartName, chartName, chartVersion string, err error) {
-	chartVersion = "latest"
-	if release.Version != "" {
+func (st *HelmState) getOCIQualifiedChartName(release *ReleaseSpec, helm helmexec.Interface) (string, string, string, error) {
+	chartVersion := "latest"
+	if st.isDevelopment(release) && release.Version == "" {
```
Comment (purpleclay) [inline pkg/state/state.go:3920]: `--devel` can only be set (_and is effective_) if a release version is not set

File: pkg/state/state.go [hunk 4]
```diff
@@ -3915,31 +3915,36 @@ func (st *HelmState) IsOCIChart(chart string) bool {
...
+		// omit version, otherwise --devel flag is ignored by helm and helm-diff
+		chartVersion = ""
```
Comment (purpleclay) [inline pkg/state/state.go:3922]: `--devel` can only be set (_and is effective_) if a release version is not set

**Comment by yxxhero** [comment]
@purpleclay cool.LGTM

**Review by yxxhero — APPROVED** [review]
