### PR TITLE
Fix not to ignore diff selector when it matched nothing

### LINKED ISSUE #327: Diff selector does not work on "installed: false" releases
### Operating system

macOS 12.5.1, alpine 3.13

### Helmfile Version

0.145.4

### Helm Version

3.5.3

### Bug description

`--selector` option with `diff` command does not narrow the diff to the selected release when the release is set to not installed by `installed: false` key; this includes running with `--skip-needs=true  --include-needs=false` flags. Diff appears to run for all releases in the same helmfile as the targeted release, including the targeted release (so it still reports it as deleted). The selector being used is a basic `name=foo` selector that should match only one release.

### Example helmfile.yaml

- name: ingress-nginx-enabled
  namespace: default
  chart: ingress-nginx/ingress-nginx

- name: ingress-nginx-disabled
  namespace: default
  installed: false
  chart: ingress-nginx/ingress-nginx

### Error message you've seen (if any)

no error messages

### Steps to reproduce

Have a helmfile with multiple releases. Set `installed: false` on one, run `helmfile --selector name=nameofthedisabledrelease diff --skip-needs`

### Working Helmfile Version

n/a

### Relevant discussion

_No response_

### PR DESCRIPTION
**Pull request by mumoshu**
Fixes #327

Signed-off-by: Yusuke Kuoka <ykuoka@gmail.com>

### CODE REVIEW

File: pkg/app/app_diff_test.go [hunk 1]
```diff
@@ -321,3 +321,150 @@ releases:
...
+foo 	4       	Fri Nov  1 08:40:07 2019	DEPLOYED	raw-3.1.0	3.1.0      	default
+`,
+			},
+			diffed: []exectest.Release{
+				{Name: "a", Flags: []string{"--kube-context", "default", "--namespace", "default"}},
+			},
+		})
+	})
+
+	t.Run("shows no diff on already uninstalled selected release", func(t *testing.T) {
```
Comment (mumoshu) [inline pkg/app/app_diff_test.go:452]: This test had been failing before the fix, due to a bug that helmfile completely ignored the selector when the selector along with `installed` filter returned no releases.

**Review by yxxhero — APPROVED** [review]
LGTM
