### PR TITLE
fix(oci): use output-dir-template in path if specified

### LINKED ISSUE #928: --output-dir-template is broken for OCI registries
### Operating system

Windows 10

### Helmfile Version

0.155.0

### Helm Version

v3.12.1

### Bug description

When using a simple fetch command to pull an OCI chart into a custom directory via helmfile, the `--output-dir-template` is not working.

Using: `helmfile -l name=my-release fetch --output-dir "../charts/" --output-dir-template "{{ .OutputDir }}"`

I would expect that the chart is pulled into `../charts/custom-chart`. Instead, the chart is pulled into something like

`../charts/default/my-release/custom-chart/^1.0.0/custom-chart` which looks like the default structure.

I need to access parts of the chart in a prepare hook. The deeply nested structure makes a this tedious task..

**This issue only applies to charts pulled via OCI registries**. Classical chart repos work as expected.

### Example helmfile.yaml

```yaml
repositories:
  - name: ocirepo
    url: registry.example.com
    oic: true

releases:
  - name: my-release
    namespace: default
    chart: ocirepo/custom-chart
    version: "^1.0.0"
```

### Error message you've seen (if any)

no errors.

### Steps to reproduce

`helmfile -l name=my-release fetch --output-dir "../charts/" --output-dir-template "{{ .OutputDir }}"`

### Working Helmfile Version

not sure if this worked at all at some point

### Relevant discussion

_No response_

### PR DESCRIPTION
**Pull request by henkka**
fixes #928

Previously `--output-dir-template` was not used if the repository was OCI.

# Test case

## `helmfile.yaml`

```yaml
repositories:
  - name: karpenter
    url: public.ecr.aws/karpenter
    oci: true
  - name: gatekeeper
    url: https://open-policy-agent.github.io/gatekeeper/charts

releases:
  - name: karpenter
    chart: karpenter/karpenter
    version: "0.37.0"
  - name: gatekeeper
    chart: gatekeeper/gatekeeper
```

## Command

```
helmfile fetch --output-dir charts --output-dir-template "{{ .OutputDir }}/"
```

# Results

## Previously

```
charts
├── gatekeeper
│   ├── Chart.yaml
│   ├── README.md
│   ├── crds
│   │   ├── assign-customresourcedefinition.yaml
│   │   ├── assignimage-customresourcedefinition.yaml
│   │   ├── assignmetadata-customresourcedefinition.yaml
│   │   ├── config-customresourcedefinition.yaml
│   │   ├── constraintpodstatus-customresourcedefinition.yaml
│   │   ├── constrainttemplate-customresourcedefinition.yaml
│   │   ├── constrainttemplatepodstatus-customresourcedefinition.yaml
│   │   ├── expansiontemplate-customresourcedefinition.yaml
│   │   ├── expansiontemplatepodstatus-customresourcedefinition.yaml
│   │   ├── modifyset-customresourcedefinition.yaml
│   │   ├── mutatorpodstatus-customresourcedefinition.yaml
│   │   ├── provider-customresourcedefinition.yaml
│   │   └── syncset-customresourcedefinition.yaml
│   ├── templates
│   │   ├── _helpers.tpl
│   │   ├── gatekeeper-admin-podsecuritypolicy.yaml
│   │   ├── gatekeeper-admin-serviceaccount.yaml
│   │   ├── gatekeeper-audit-deployment.yaml
│   │   ├── gatekeeper-controller-manager-deployment.yaml
│   │   ├── gatekeeper-controller-manager-network-policy.yaml
│   │   ├── gatekeeper-controller-manager-poddisruptionbudget.yaml
│   │   ├── gatekeeper-critical-pods-resourcequota.yaml
│   │   ├── gatekeeper-manager-role-clusterrole.yaml
│   │   ├── gatekeeper-manager-role-role.yaml
│   │   ├── gatekeeper-manager-rolebinding-clusterrolebinding.yaml
│   │   ├── gatekeeper-manager-rolebinding-rolebinding.yaml
│   │   ├── gatekeeper-mutating-webhook-configuration-mutatingwebhookconfiguration.yaml
│   │   ├── gatekeeper-validating-webhook-configuration-validatingwebhookconfiguration.yaml
│   │   ├── gatekeeper-webhook-server-cert-secret.yaml
│   │   ├── gatekeeper-webhook-service-service.yaml
│   │   ├── namespace-post-install.yaml
│   │   ├── namespace-post-upgrade.yaml
│   │   ├── probe-webhook-post-install.yaml
│   │   ├── upgrade-crds-hook.yaml
│   │   └── webhook-configs-pre-delete.yaml
│   └── values.yaml
└── karpenter
    └── karpenter
        └── 0.37.0
            └── karpenter
                ├── Chart.lock
                ├── Chart.yaml
                ├── README.md
                ├── README.md.gotmpl
                ├── artifacthub-repo.yaml
                ├── crds
                │   ├── karpenter.k8s.aws_ec2nodeclasses.yaml
                │   ├── karpenter.sh_nodeclaims.yaml
                │   └── karpenter.sh_nodepools.yaml
                ├── templates
                │   ├── _helpers.tpl
                │   ├── aggregate-clusterrole.yaml
                │   ├── clusterrole-core.yaml
                │   ├── clusterrole.yaml
                │   ├── configmap-logging.yaml
                │   ├── deployment.yaml
                │   ├── poddisruptionbudget.yaml
                │   ├── role.yaml
                │   ├── rolebinding.yaml
                │   ├── secret-webhook-cert.yaml
                │   ├── service.yaml
                │   ├── serviceaccount.yaml
                │   ├── servicemonitor.yaml
                │   ├── webhooks-core.yaml
                │   └── webhooks.yaml
                └── values.yaml

10 directories, 61 files
```

## Now

```
charts
├── gatekeeper
│   ├── Chart.yaml
│   ├── README.md
│   ├── crds
│   │   ├── assign-customresourcedefinition.yaml
│   │   ├── assignimage-customresourcedefinition.yaml
│   │   ├── assignmetadata-customresourcedefinition.yaml
│   │   ├── config-customresourcedefinition.yaml
│   │   ├── constraintpodstatus-customresourcedefinition.yaml
│   │   ├── constrainttemplate-customresourcedefinition.yaml
│   │   ├── constrainttemplatepodstatus-customresourcedefinition.yaml
│   │   ├── expansiontemplate-customresourcedefinition.yaml
│   │   ├── expansiontemplatepodstatus-customresourcedefinition.yaml
│   │   ├── modifyset-customresourcedefinition.yaml
│   │   ├── mutatorpodstatus-customresourcedefinition.yaml
│   │   ├── provider-customresourcedefinition.yaml
│   │   └── syncset-customresourcedefinition.yaml
│   ├── templates
│   │   ├── _helpers.tpl
│   │   ├── gatekeeper-admin-podsecuritypolicy.yaml
│   │   ├── gatekeeper-admin-serviceaccount.yaml
│   │   ├── gatekeeper-audit-deployment.yaml
│   │   ├── gatekeeper-controller-manager-deployment.yaml
│   │   ├── gatekeeper-controller-manager-network-policy.yaml
│   │   ├── gatekeeper-controller-manager-poddisruptionbudget.yaml
│   │   ├── gatekeeper-critical-pods-resourcequota.yaml
│   │   ├── gatekeeper-manager-role-clusterrole.yaml
│   │   ├── gatekeeper-manager-role-role.yaml
│   │   ├── gatekeeper-manager-rolebinding-clusterrolebinding.yaml
│   │   ├── gatekeeper-manager-rolebinding-rolebinding.yaml
│   │   ├── gatekeeper-mutating-webhook-configuration-mutatingwebhookconfiguration.yaml
│   │   ├── gatekeeper-validating-webhook-configuration-validatingwebhookconfiguration.yaml
│   │   ├── gatekeeper-webhook-server-cert-secret.yaml
│   │   ├── gatekeeper-webhook-service-service.yaml
│   │   ├── namespace-post-install.yaml
│   │   ├── namespace-post-upgrade.yaml
│   │   ├── probe-webhook-post-install.yaml
│   │   ├── upgrade-crds-hook.yaml
│   │   └── webhook-configs-pre-delete.yaml
│   └── values.yaml
└── karpenter
    ├── Chart.lock
    ├── Chart.yaml
    ├── README.md
    ├── README.md.gotmpl
    ├── artifacthub-repo.yaml
    ├── crds
    │   ├── karpenter.k8s.aws_ec2nodeclasses.yaml
    │   ├── karpenter.sh_nodeclaims.yaml
    │   └── karpenter.sh_nodepools.yaml
    ├── templates
    │   ├── _helpers.tpl
    │   ├── aggregate-clusterrole.yaml
    │   ├── clusterrole-core.yaml
    │   ├── clusterrole.yaml
    │   ├── configmap-logging.yaml
    │   ├── deployment.yaml
    │   ├── poddisruptionbudget.yaml
    │   ├── role.yaml
    │   ├── rolebinding.yaml
    │   ├── secret-webhook-cert.yaml
    │   ├── service.yaml
    │   ├── serviceaccount.yaml
    │   ├── servicemonitor.yaml
    │   ├── webhooks-core.yaml
    │   └── webhooks.yaml
    └── values.yaml

7 directories, 61 files
```

### CODE REVIEW

**Comment by yxxhero** [comment]
@henkka  could you add some test for this?

**Comment by henkka** [comment]
> @henkka could you add some test for this?

Sure! In https://github.com/helmfile/helmfile/pull/1648/commits/e0c754134d9bde5d44217ee51165d6b7e19e2ae1 I extracted the OCI chart path logic to its own function and created simple tests for it.

File: pkg/state/state.go [hunk 1]
```diff
@@ -3754,3 +3740,27 @@ func (st *HelmState) FullFilePath() (string, error) {
...
 	return filepath.Join(wd, st.basePath, st.FilePath), err
 }
+
+func (st *HelmState) getOCIChartPath(tempDir string, release *ReleaseSpec, chartName, chartVersion, outputDirTemplate string) (string, error) {
+	if outputDirTemplate != "" {
+		chartPath, err := generateChartPath(chartName, tempDir, release, outputDirTemplate)
+		if err != nil {
+			return "", err
+		}
+		return chartPath, nil
```
Comment (yxxhero) [inline pkg/state/state.go:3750]:
```suggestion
		return generateChartPath(chartName, tempDir, release, outputDirTemplate)
```

Comment (yxxhero) [reply pkg/state/state.go:3750]: WDYT?

**Review by yxxhero — APPROVED** [review]
