### PR TITLE
Use goccy/go-yaml for v1 / Prep bringing back go-yaml v2 for v0.x

### LINKED ISSUE #435: `.Release.Labels` are not available within values templates
### Operating system

macOS Monterey Version 12.5

### Helmfile Version

0.147.0

### Helm Version

3.10.1

### Bug description

Since 0.147.0 it seems like `.Release.Labels` are no longer available to use within values templates.
Same example works fine with previous releases. 

### Example helmfile.yaml

helmfile.yaml:
```
repositories:
  - name: jenkinsci
    url: https://charts.jenkins.io
 
templates:
  jenkins: &jenkins
    name: jenkins{{`{{.Release.Labels.jenkinsInstance}}`}}
    chart: jenkinsci/jenkins
    version: 4.1.16
    labels:
      group: jenkins
      privateRegistry: 123456789.dkr.ecr.us-west-1.amazonaws.com
    namespace: jenkins{{`{{.Release.Labels.jenkinsInstance}}`}}
    values:
      - jenkins.yaml.gotmpl

releases:
  - labels:
      jenkinsInstance: "1"
      zone: us-west-1b
      branch: master
      jobsTags: ""
    <<: *jenkins
```

jenkins.yaml.gotmpl:
```
agent:
  image: '{{ .Release.Labels.privateRegistry }}/jenkins-agent'
```

### Error message you've seen (if any)

in ./helmfile.yaml: failed to render values files "jenkins.yaml.gotmpl": failed to render [jenkins.yaml.gotmpl], because of template: stringTemplate:2:21: executing "stringTemplate" at <.Release.Labels.privateRegistry>: map has no entry for key "privateRegistry"

### Steps to reproduce

helmfile -f ./helmfile.yaml -l name=jenkins1 template

### Working Helmfile Version

0.146.0

### Relevant discussion

_No response_

### PR DESCRIPTION
**Pull request by mumoshu**
This is a successor to #596. We need a smooth migration path from `gopkg.in/yaml.v2`, and this pull request moves it forward with `goccy/go-yaml` instead of `gopkg.in/yaml.v3`. Merging this unblocks users stuck in Helmfile v0.146.x or earlier due to #435, so that they can upgrade to 0.147.x or greater without updating their helmfile configs.

We previously tried to upgrade to `yaml.v3` (https://github.com/helmfile/helmfile/issues/394) in Helmfile v0.x, presuming it won't break anything. Apparently, it broke use-cases where you want to layer release's `values` field over three or more release templates and releases (#435).

We then tried to bring back `yaml.v2` for Helmfile v0.x and keep `yaml.v3` for the upcoming Helmfile v1. However, it failed due to incompatibility in the Unmarshaller interface between `yaml.v2` and `yaml.v3` (https://github.com/helmfile/helmfile/pull/596).

`goccy/go-yaml` is, from my observation, a well-maintained alternative to `yaml.v2`. One of its premises is that it enables us to swap the implementation from `gopkg.in/yaml.v2` to `goccy/go-yaml` just by replacing the import directive. It seems to use the same `Unmarshaller` interface as yaml.v2 too.

Once this PR gets merged, I'd like to follow-up with adding a new build-time variable and an envvar to set the proper default for the yaml parser Helmfile uses and the ability to switch the parser at runtime. All in all, the next Helmfile release, v0.150.0 will get reverted to use `gopkg.in/yaml.v2` by default which resolves #435.

New users who started using Helmfile since any of v0.148.0, v0.148.1, and v0.149.0 might be already relying on the new behavior, They might need to specify a new envvar to enable `goccy/go-yaml`.

Ref #435

Signed-off-by: Yusuke Kuoka <ykuoka@gmail.com>

### CODE REVIEW

File: pkg/app/app_list_test.go [hunk 1]
```diff
@@ -242,7 +242,7 @@ environments:
 releases:
 - name: myrelease1
   chart: mychart1
-  installed: no
```
Comment (mumoshu) [inline pkg/app/app_list_test.go:245]: It turned out on/off and yes/no are deprecated in YAML 1.2.
https://github.com/goccy/go-yaml/issues/214

To make it backward-compatible for Helmfile v.0x, I'd like to revert Helmfile v0.x to use `gopkg.in/yaml.v2` by default.
Let feature the deprecation in the helmfile v1 proposal and enable goccy/go-yaml only for Helmfile v1, so that we won't break anything for Helmfile v0.x while we can still migrate to a maintained yaml library.

Comment (yxxhero) [reply pkg/app/app_list_test.go:245]: ok

**Comment by yxxhero** [comment]
@mumoshu all is ok. I fixed the test cases. please review again

**Review by yxxhero — DISMISSED** [review]
LGTM  great work.

**Comment by yxxhero** [comment]
whrer is then `MarshalYAML` and `UnmarshalYAML`?

File: pkg/state/state.go [hunk 2]
```diff
@@ -87,25 +86,27 @@ type ReleaseSetSpec struct {
...
 type helmStateAlias HelmState
 
-func (hs HelmState) MarshalYAML() (interface{}, error) {
-	return helmStateAlias(hs), nil
+func (hs HelmState) MarshalYAML() ([]byte, error) {
+	hsa := helmStateAlias(hs)
+	return yaml.Marshal(hsa)
 }
 
-func (hs *HelmState) UnmarshalYAML(value *yaml.Node) error {
```
Comment (mumoshu) [inline pkg/state/state.go:94]: @yxxhero I believe you can revert 589576e and make it back to use `UnmarshalYaml(func(interface{}) error) error`, as that's what we've been implementing when we were originally using gopkg.in/yaml.v2 alone and goccy/go-yaml does support the exact interface too https://github.com/goccy/go-yaml/blob/6cdefc42e112ac71cbe316e1eed264ea62f58e25/yaml.go#L49-L52

File: pkg/state/state.go [hunk 3]
```diff
@@ -87,25 +86,27 @@ type ReleaseSetSpec struct {
 // helmStateAlias is helm state alias
 type helmStateAlias HelmState
 
-func (hs HelmState) MarshalYAML() (interface{}, error) {
```
Comment (mumoshu) [inline pkg/state/state.go:90]: @yxxhero Same for MarshalYAML. goccy/go-yaml does support InterfaceMarshaller and expect the MarshalYAML function to return a Go object that is then serialized into YAML rather than a raw byte array that is embedded into the resulting YAML document as-is.

https://github.com/goccy/go-yaml/blob/6cdefc42e112ac71cbe316e1eed264ea62f58e25/yaml.go#L28-L31

File: pkg/state/state.go (hunk 2 above)
Comment (yxxhero) [reply pkg/state/state.go:94]: HelmState's UnmarshalYAML was created for v1, and I feel like it can be adapted to the latest goccy/go-yaml interface, which I don't need to introduce for v0. @mumoshu

File: pkg/state/state.go (hunk 3 above)
Comment (yxxhero) [reply pkg/state/state.go:90]: HelmState's MarshalYAML was created for v1, and I feel like it can be adapted to the latest goccy/go-yaml interface, which I don't need to introduce for v0.

File: pkg/state/state.go (hunk 2 above)
Comment (mumoshu) [reply pkg/state/state.go:94]: I've updated my comment before you replied! Sorry for the confusion. Regardless of when it was introduced first, I think the problem of using the new interface seems to have been caught by the test failure- it now does not intend nested YAML dicts correctly.

File: pkg/state/state.go (hunk 3 above)
Comment (mumoshu) [reply pkg/state/state.go:90]: Thanks for your reply! See https://github.com/helmfile/helmfile/pull/604#discussion_r1057009477

File: pkg/state/state.go (hunk 2 above)
Comment (yxxhero) [reply pkg/state/state.go:94]: yes. should we post an issue to goccy/go-yaml?

Comment (mumoshu) [reply pkg/state/state.go:94]: Why? We don't need to stick with `MarshalYAML() ([]byte, error) {`  nor `UnmarshalYAML(b []byte) error`, right?
Or do you know anything that isn't covered by our current test suite?

Comment (mumoshu) [reply pkg/state/state.go:94]: Note that all the tests were passing at [b2515a7](https://github.com/helmfile/helmfile/pull/604/commits/b2515a7a6d48601a59bf76faf05965ff91c0b770)

Comment (mumoshu) [reply pkg/state/state.go:94]: @yxxhero Maybe you wanted to keep using the `UnmarshalYAML(b []byte) error` assuming assuming it would be needed for the strict parsing even for goccy/go-yaml, right?

Comment (mumoshu) [reply pkg/state/state.go:94]: Apparently goccy's respect strict parsing setting even you used InterfaceUnmarshaller to unmarshal nested structs. See https://github.com/goccy/go-yaml/blob/6cdefc42e112ac71cbe316e1eed264ea62f58e25/decode.go#L626 and https://github.com/goccy/go-yaml/blob/6cdefc42e112ac71cbe316e1eed264ea62f58e25/decode.go#L1045-L1050.

It would be great if we could add a new test case to test the desired behavior though... Any idea about that?

Comment (yxxhero) [reply pkg/state/state.go:94]: yeah. I think so. when use `UnmarshalYAML(b []byte) error` for `HelmState`. we need a strict mode to keep the same behavior with the `yaml.UnMarshal`.

Comment (yxxhero) [reply pkg/state/state.go:94]: @mumoshu

Comment (mumoshu) [reply pkg/state/state.go:94]: @yxxhero I've reverted UnmarshalYAML and added a new test to ensure that it does respect the UnknownField option. The test is passing. WDYT?
https://github.com/helmfile/helmfile/pull/604/commits/d323cc1841997d0467404cead63de6ecf5c56e56

File: pkg/state/state.go (hunk 3 above)
Comment (mumoshu) [reply pkg/state/state.go:90]: @yxxhero Have you seen some tests failing due to diffs like the below?

```
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -17,6 +17,6 @@
        	            	 metadata:
        	            	-  name: foo-2
        	            	-  namespace: default
        	            	+name: foo-2
        	            	+namespace: default
        	            	 data:
        	            	-  bar: BAR
        	            	+bar: BAR
        	            	 ---
        	            	@@ -26,6 +26,6 @@
        	            	 metadata:
        	            	-  name: foo-1
        	            	-  namespace: default
        	            	+name: foo-1
        	            	+namespace: default
        	            	 data:
        	            	-  foo: FOO
        	            	+foo: FOO
```

I think this indicates that MarshalYAML changes from https://github.com/helmfile/helmfile/pull/604/commits/589576e0111687298089b2e0cb57701b3703eda7 is unnecessary.

Comment (yxxhero) [reply pkg/state/state.go:90]: yeah. I saw it. and I tried to solve this issue. but it's because goccy/yaml logic issue. I already post an issue for this.

File: pkg/state/state.go (hunk 2 above)
Comment (yxxhero) [reply pkg/state/state.go:94]: good work.

**Review by yxxhero — APPROVED** [review]

**Comment by mumoshu** [comment]
@yxxhero Thank you so much for your throughout review and confirmation ❤️
