### PR TITLE
Make helmfile respect signals send by kill command (not only Ctrl+C in terminal)

### LINKED ISSUE #746: Signal handling seems to not work as expected
### Operating system

MacOS 13.2.1

### Helmfile Version

 ▓▓▓ helmfile    Version            v0.151.0   Git Commit         "brew"   Build Date         17 Feb 23 08:09 EET (3 weeks ago)   Commit Date        17 Feb 23 08:09 EET (3 weeks ago)   Dirty Build        no   Go version         1.19.6   Compiler           gc   Platform           darwin/arm64

### Helm Version

version.BuildInfo{Version:"v3.11.2", GitCommit:"912ebc1cd10d38d340f048efaf0abda047c3468e", GitTreeState:"clean", GoVersion:"go1.20.2"}

### Bug description

When I'm trying to interrupt helmfile apply by `Ctrl+C` from console all works as expected, release is marked as failed and I'm getting `Canceled` messages in stderr.

But when I'm trying to interrupt helmfile by sending signals using kill (`kill -2 <pid>`, `kill -15 <pid>`) helmfiles just ignores them. So I find that only `kill -9 <pid>` is working, but of course -9 just kills process without marking releases as failed.

This errors seems to be not only limited to MacOS, cause workflow canceling in my Github Actions workflow is also not handled properly.

### Example helmfile.yaml

Doesn't matter

### Error message you've seen (if any)

No

### Steps to reproduce

Start long running helmfile apply, send SIGINT/SIGTERM using the kill from another terminal

### Working Helmfile Version

No

### Relevant discussion

_No response_

### PR DESCRIPTION
**Pull request by dm3ch**
/fix #746

### CODE REVIEW

**Comment by dm3ch** [comment]
As far as I understand the signal handling code (https://github.com/helmfile/helmfile/blob/main/main.go#L29-L40) should live in lambda function (https://github.com/helmfile/helmfile/blob/main/main.go#L20-L22) to be able to be handled immediately.

In my experiment moving mentioned logic to lambda and adding debug print I ensured, that signal is handled immediately (even when it's send by kill).

Unfortunately I don't understand how CleanWaitGroup supposed to work. So my change just hangs up on CleanWaitGroup and waits until successful end of apply (not propagates a signal to child processes)

**Comment by dm3ch** [comment]
I tried to just drop CleanWaitGroup.Wait() and all works as I expect, except cleaning temporary files.

**Comment by dm3ch** [comment]
@yxxhero Can you please take a look? So far I have no idea how to better exec cleanup from lambda/propograte cancel context.

Maybe you can point me to the right direction, please?

**Comment by yxxhero** [comment]
@dm3ch please fix ci issue.

**Comment by yxxhero** [comment]
@dm3ch you can use golangci-lint as your lint tool. it will help you automatically check lint errors.

**Comment by dm3ch** [comment]
> @dm3ch please fix ci issue.

It seems that now tests and lint should be fixed.
But I'm not sure that it's effective to fix tests and lint when code changes itself are awful themselves. :)

**Comment by yxxhero** [comment]
When test is ok. We will review the code.

**Comment by dm3ch** [comment]
Missed some of failed, would try to fix

**Comment by dm3ch** [comment]
@yxxhero Fixed race condition, can you please run tests one more time?

**Comment by yxxhero** [comment]
> @yxxhero Fixed race condition, can you please run tests one more time?

sure.

**Comment by yxxhero** [comment]
@dm3ch is it ready to review?

**Comment by dm3ch** [comment]
> @dm3ch is it ready to review?

Yes

**Comment by mumoshu** [comment]
@dm3ch Hey! Thanks a lot for your contribution. This looks good so far. A quick confirmation though- is this supposed to fix the issue by letting helmfile explicitly cancel the running commands (like helm) on SIGTERM/SIGINT?

I presume Ctrl-C worked just because it sends SIGINT to both the helmfile and its child processes, whereas `kill -SIGINT` just sends it to the helmfile process so helmfile needs to cancel/wait for children depending on the situation.

Is my understanding correct? I'd really appreciate it if you could correct any details/mistakes in my understanding because I'd like to be 100% sure this doesn't break anything/does fix the issue! Thanks.

**Comment by yxxhero** [comment]
@mumoshu good question.

**Comment by dm3ch** [comment]
@mumoshu After some time of researching this phenomenon I also resulted in theory that bash is sending SIGINT to both parent and child process (process group).

So If I right understand before this change sig handling in helmfile wasn't the thing that actually triggered exit. The exit was the result of helm exit with != 0 exit code.

With my changes exit is also triggered by helm exit code != 0, but I pass SIGINT to the helm process in case helmfile received SIGINT.

File: main.go [hunk 1]
```diff
@@ -38,6 +31,13 @@ func main() {
 				os.Exit(143)
```
Comment (yxxhero) [inline main.go:31]: os.Exit in a goroutine?

Comment (dm3ch) [reply main.go:31]: I think you are right that it's not the best solution.

As far as I understand this behaviour is save, cause exit called only after waiting for a cleanup group and os.Exit as far as I understood termintates all routines.

What would you propose to improve this?

Comment (yxxhero) [reply main.go:31]: @dm3ch The work is awesome. I will try to work on this issue. when this is ready. v0.152.0 will be released.

**Comment by dm3ch** [comment]
LGTM

**Comment by yxxhero** [comment]
@dm3ch could you help me to test?

**Comment by dm3ch** [comment]
> @dm3ch could you help me to test?

Tested, works fine in my case, temp files were cleaned properly

**Comment by yxxhero** [comment]
@dm3ch Thanks for your feedback.

File: pkg/helmexec/exec.go [hunk 2]
```diff
@@ -110,7 +112,7 @@ func redactedURL(chart string) string {
 }
 
 // New for running helm commands
-func New(helmBinary string, enableLiveOutput bool, logger *zap.SugaredLogger, kubeContext string, runner Runner) *execer {
+func New(helmBinary string, enableLiveOutput bool, logger *zap.SugaredLogger, kubeContext string, runner Runner, ctx context.Context) *execer {
```
[the remark this answers is not in the document]
Comment (dm3ch) [reply pkg/helmexec/exec.go]: Fixed

**Comment by dm3ch** [comment]
@yxxhero I have resolved conflicts. Can you please approve CI?

**Comment by dm3ch** [comment]
BTW, what we are waiting for? Are we waiting a review from other maintainers?

File: pkg/event/bus_test.go [hunk 3]
```diff
@@ -15,11 +16,11 @@ import (
 type runner struct {
 }
 
-func (r *runner) ExecuteStdIn(cmd string, args []string, env map[string]string, stdin io.Reader) ([]byte, error) {
```
Comment (mumoshu) [inline pkg/event/bus_test.go:18]: Sorry for the radio silence! I'm reviewing this today. Although almost everything looks awesome, I have one enhancement idea-

Can we safely move the ctx to the runner struct field, rather than adding the ctx parameter? That way we can avoid changing every call to ExecuteStdIn and Exexcute.

We already have the ctx in the helmExecer field, instead of adding the ctx parameters to all the helmExecer methods. It should e feasible todo the same for `runner`, assuming the life time of a `runner` would be same as its caller/parent, `helmExecer`. WDYT? 🤔

Comment (mumoshu) [reply pkg/event/bus_test.go:18]: // I'll try changing it this way myself when I have some time.

Comment (dm3ch) [reply pkg/event/bus_test.go:18]: Such change seems to be reasonable. If I right remember I haven't done that just because I haven't found a constructor that would allow me to do that

Comment (dm3ch) [reply pkg/event/bus_test.go]: Done. But I ignored the bus.go codepath where runner is initialised separately for the hooks if it wasn't passed

**Comment by dm3ch** [comment]
I don't understand what's wrong with integration tests:
- One of jobs seems to have timeout to github API
- Another job, I don't understand at all what's wrong.

I would be glad if someone would point me what's wrong

**Comment by yxxhero** [comment]
rerun

**Comment by yxxhero** [comment]
@mumoshu WDYT about new changes?

**Review by mumoshu — APPROVED** [review]
@dm3ch Sorry for the delayed review! This looks perfect now. Thanks a lot for your contribution!

FYI here's my test report for this https://github.com/helmfile/helmfile/issues/746#issuecomment-1528682934
