### PR TITLE
fix: resolve issues #2295, #2296, and #2297

### LINKED ISSUE #2295: Cache conflicts running multiple helmfile using the same chart in parallel
### Operating system

Fedora 43

### Helmfile Version

1.2.1

### Helm Version

v3.17.1

### Bug description

We run multiple helmfile in parallel, in `1.1.0`, OCI charts where downloaded to a unique folder in `/tmp`
```
/tmp/helmfile4292931928/karpenter/testetienne/ingress-nodepool/charts/incubator/raw/0.2.5/raw
```

In `1.2.1`, the  folder is deterministic
```
/home/user/.cache/helmfile/ecr/charts/incubator/raw/0.2.5
```

If 2 helmfile using the same chart run in parallel, they will run the same `helm pull` command in parallel and we can have conflicts
```
Error: failed to untar: a file or directory with the name /home/user/.cache/helmfile/ecr/charts/incubator/raw/0.2.5/raw already exists
```

The new behavior change was added in #2171

### Example helmfile.yaml

I can write a minimal helmfile.yaml if really needed

### Error message you've seen (if any)

```
Error: failed to untar: a file or directory with the name /home/user/.cache/helmfile/ecr/charts/incubator/raw/0.2.5/raw already exists
```

### Steps to reproduce

todo

### Working Helmfile Version

1.1.0

### Relevant discussion

https://github.com/helm/helm/issues/12315

### LINKED ISSUE #2296: .helmDefaults.skipDeps and .helmDefaults.skipRefresh are ignored
### Operating system

linux

### Helmfile Version

1.2.1

### Helm Version

v3.19.0

### Bug description

`--skip-deps` and `--skip-refresh` work as expected
setting `skipDeps` and/or `skipRefresh` has no effect

```
helmfile -e dev -l name=some-release diff --skip-deps 
Decrypting secret .../secrets.yaml
Comparing release=some-release, chart=/home/gfdsa/.cache/helmfile/some-chart, namespace=dev
```
```
helmfile -e dev -l name=some-release diff --skip-refresh
Decrypting secret .../secrets.yaml
Comparing release=some-release, chart=/home/gfdsa/.cache/helmfile/some-chart, namespace=dev
```
```
helmfile -e dev -l name=some-release diff
Decrypting secret .../secrets.yaml
Adding repo bedag https://bedag.github.io/helm-charts/
"bedag" has been added to your repositories

Adding repo stakater https://stakater.github.io/stakater-charts
"stakater" has been added to your repositories

Adding repo mailpit https://jouve.github.io/charts
"mailpit" has been added to your repositories

Pulling some-chart:some-tag

Comparing release=some-release, chart=/home/gfdsa/.cache/helmfile/some-chart, namespace=dev
```
```
yq .helmDefaults  helmfile.yaml.gotmpl | head
skipDeps: true
skipRefresh: true
```

### Example helmfile.yaml

```
missingFileHandler: Error

bases:
  - environments/{{ requiredEnv "PRODUCT_NAME" }}/environments.yaml

helmDefaults:
  skipDeps: true
  skipRefresh: true
  wait: true
  waitForJobs: true
  timeout: 600
  force: true
  historyMax: 10
  createNamespace: true
  suppressOutputLineRegex:
    - "helm.sh/chart"
    - "chart"
    - "app.kubernetes.io/version"
    - "checksum/config"

repositories:
  - name: bedag
    url: https://bedag.github.io/helm-charts/
  - name: bitnami
    url: docker.io/bitnamicharts
    oci: true
  - name: stakater
    url: https://stakater.github.io/stakater-charts
  - name: oauth2-proxy
    #url: https://oauth2-proxy.github.io/manifests
    url: ghcr.io/oauth2-proxy/charts
    oci: true
  - name: mailpit
    url: https://jouve.github.io/charts

```

### Error message you've seen (if any)

no errors, skip is not mentioned in debug

### Steps to reproduce

run as above with skip attributes ignored

### Working Helmfile Version

none

### Relevant discussion

_No response_

### LINKED ISSUE #2297: helmfile 1.2.1 fails with multiple release files using local chart and transformers
### Operating system

Debian 12, Ubuntu 24.04

### Helmfile Version

1.2.1

### Helm Version

version.BuildInfo{Version:"v3.19.2", GitCommit:"8766e718a0119851f10ddbe4577593a45fadf544", GitTreeState:"clean", GoVersion:"go1.24.9"}

### Bug description

After upgrading from 1.1.9 to 1.2.1 helmfile started crashing in one of my deployments.

I've managed to narrow it down to following conditions:

- several releases in different files inside `helmfile.d`
- one of the releases must use charts from local directory
- this release also must have `transformers` applied to them

The same release renders OK if I remove `transformers` from release file.

### Example helmfile.yaml

See provided reproduction repo for minial config and steps to reproduce

### Error message you've seen (if any)

```
panic: BUG: please file an github issue for this unhandled error: *errors.errorString: [exit status 1

        COMMAND:
          helm pull ../chart --untar -d /tmp/chartify3348756149/with-transformers

        OUTPUT:
          Error: repo .. not found]

goroutine 12 [running]:
github.com/helmfile/helmfile/cmd.toCLIError(0xc000746240?, {0x5afe620?, 0xc00091c650?})
        /home/runner/work/helmfile/helmfile/cmd/root.go:38 +0x268
github.com/helmfile/helmfile/cmd.NewTemplateCmd.func1(0xc000f06a00?, {0x51f5319?, 0x4?, 0x51f540d?})
        /home/runner/work/helmfile/helmfile/cmd/template.go:29 +0x117
github.com/spf13/cobra.(*Command).execute(0xc00108ac08, {0xc0004fa1a0, 0x2, 0x2})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.10.1/command.go:1015 +0xb02
github.com/spf13/cobra.(*Command).ExecuteC(0xc000cd3b08)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.10.1/command.go:1148 +0x465
github.com/spf13/cobra.(*Command).Execute(0xc0001c9a40?)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.10.1/command.go:1071 +0x13
main.main.func1()
        /home/runner/work/helmfile/helmfile/main.go:29 +0x69
created by main.main in goroutine 1
        /home/runner/work/helmfile/helmfile/main.go:21 +0xcf
```

### Steps to reproduce

https://github.com/vgivanov/helmfile-1.2-regression-reproduction

### Working Helmfile Version

1.1.9

### Relevant discussion

_No response_

### PR DESCRIPTION
**Pull request by aditmeno**
## Summary

This PR fixes four related bugs that affect chart preparation, caching, and OCI registry authentication:

### Issue #2295: OCI chart cache conflicts with parallel helmfile processes
**Problem:** When running multiple helmfile processes in parallel using the same OCI chart, race conditions cause "file already exists" errors due to concurrent cache writes.

**Solution:**
- Added filesystem-level locking using `flock` for cross-process synchronization
- Uses reader-writer locks: shared locks (`RLock`) for reading cached charts, exclusive locks (`Lock`) for download/refresh
- Implements double-check locking pattern for efficiency (re-check cache after acquiring lock)
- **Simplified approach**: Locks are released immediately after download completes. This is safe because the `tempDir` cleanup is deferred until after helm operations complete in `withPreparedCharts()`, so charts won't be deleted mid-use
- In-memory chart cache prevents redundant downloads within a single process
- Removed the arbitrary 60s refresh marker timeout - lock-based synchronization provides proper coordination

**Files changed:** `pkg/state/state.go` (acquireChartLock, acquireSharedLock, acquireExclusiveLock, getOCIChart, forcedDownloadChart functions)

---

### Issue #2296: `helmDefaults.skipDeps` and `helmDefaults.skipRefresh` are ignored
**Problem:** CLI flags `--skip-deps` and `--skip-refresh` work correctly, but setting these in `helmfile.yaml` under `helmDefaults` has no effect - repos are still synced.

**Root cause:** `SkipRepos` was only set from CLI options in `ChartPrepareOptions`, not from `helmDefaults`.

**Solution:** Check both CLI options AND `r.state.HelmDefaults.SkipDeps`/`SkipRefresh` when deciding whether to skip repo sync.

**Files changed:** `pkg/app/run.go` (withPreparedCharts and Deps functions)

---

### Issue #2297: Local chart + transformers causes panic
**Problem:** Regression from 1.1.9 to 1.2.1. When using a local chart with a relative path (`chart: ../chart`) combined with transformers in `helmfile.d/`, helmfile fails with:
```
helm pull ../chart --untar fails with "repo .. not found"
```

**Root cause:** The relative chart path was not normalized to an absolute path before being passed to chartify. Chartify then tried to `helm pull ../chart` treating it as a remote chart reference.

**Solution:** Normalize local chart paths to absolute before calling `processChartification()`.

**Files changed:** `pkg/state/state.go` (prepareChartForRelease function)

---

### OCI Registry Login URL Fix (from PR #2301)
**Problem:** When using OCI registries with chart paths (e.g., ECR with `/charts` path), `helm registry login` would fail because the full URL was passed instead of just the registry host.

**Solution:**
- Added `extractRegistryHost()` function to extract just the registry host from OCI URLs
- e.g., `123456789012.dkr.ecr.us-east-1.amazonaws.com/charts` → `123456789012.dkr.ecr.us-east-1.amazonaws.com`
- Fixed `SyncRepos` to use the extracted host for OCI registry login

**Files changed:** `pkg/state/state.go` (extractRegistryHost, SyncRepos functions)

---

## Test Plan

- [x] Unit tests added for issue #2296 (`pkg/state/issue_2296_test.go`)
- [x] Unit tests added for issue #2297 (`pkg/state/issue_2297_test.go`)  
- [x] Unit tests added for issue #2295 (`pkg/state/oci_chart_lock_test.go`)
- [x] Unit tests added for OCI registry login (`Test_extractRegistryHost`, `TestHelmState_SyncRepos_OCI`)
- [x] Integration test added for issue #2297 (`test/integration/test-cases/issue-2297-local-chart-transformers.sh`)
- [x] Integration test added for issue #2295 (`test/integration/test-cases/oci-parallel-pull.sh`)
- [x] All existing unit tests pass (including TestLint)
- [x] Manual testing of issue #2297 fix verified transformer annotations are applied

## Breaking Changes

None. All changes are backwards compatible bug fixes.

Fixes #2295
Fixes #2296
Fixes #2297

### CODE REVIEW

**Comment by yxxhero** [comment]
@aditmeno split 3 PRs are better next time. thanks so much.

**Comment by aditmeno** [comment]
@yxxhero PR is ready for review

File: pkg/state/state.go [hunk 1]
```diff
@@ -4361,17 +4446,7 @@ func (st *HelmState) getOCIChart(release *ReleaseSpec, tempDir string, helm helm
 		}
 	}
 
-	downloadedOCIMutex.RLock()
-	alreadyDownloadedFlag := downloadedOCICharts[chartPath]
-	downloadedOCIMutex.RUnlock()
-
-	if !opts.SkipDeps && !opts.SkipRefresh && !alreadyDownloadedFlag {
-		err = os.RemoveAll(chartPath)
```
Comment (champtar) [inline pkg/state/state.go:4369]: The previous behavior was to delete / redownload to refresh,
effectively the new implementation is equivalent to forcing SkipRefresh=True, which I prefer, but might be a problem with changing tags (`latest`)

Comment (aditmeno) [reply pkg/state/state.go:4369]: I split out the first refresh into this PR - #2301, i guess I could merge it into this and close it

**Comment by aditmeno** [comment]
@champtar This concern is addressed in the merged changes from PR #2301. The new implementation does **not** force `SkipRefresh=True` - it still supports refresh (delete + re-download) while adding coordination for parallel processes.

**How it works:**

The `acquireChartLock()` function tracks `needsRefresh = !opts.SkipDeps && !opts.SkipRefresh`, so refresh behavior is preserved when the user hasn't disabled it.

When `needsRefresh=true` and the chart directory exists:
1. **First process**: Deletes the existing chart, re-downloads it, and creates a refresh marker file
2. **Parallel processes within 60 seconds**: Use the cached version (prevents race conditions like "file already exists" errors)
3. **After 60 seconds**: The marker is considered stale, so the next process will refresh again

This means:
- `--skip-refresh=false` (default): Charts are refreshed once per ~60s window (can make it configurable if it makes sense), with parallel processes coordinated
- `--skip-refresh=true`: Always uses cached version (existing behavior)

The 60-second TTL is chosen to cover a typical helmfile run duration while still allowing fresh pulls on subsequent runs. This should handle changing tags like `latest` correctly - each new helmfile invocation (after 60s) will pull the latest version.

**Comment by champtar** [comment]
@aditmeno thanks for working on this
60s is completely arbitrary, deploy that trigger scaling up/down often take more than that, so you might launch helm while the chart is deleted, or have the chart deleted while helm run.
The right way to do it IMO is to use exclusive lock when you want to refresh, and shared lock while you use the the chart.

Skipping refresh when the chart is recent is a separate issue, this is a good improvement, but the time should not be hardcoded

**Comment by aditmeno** [comment]
@champtar Thank you for the feedback! You're absolutely right about the 60s timeout being problematic. I've addressed your concerns.

**Changes made:**

1. **Replaced 60s timeout with proper reader-writer locks** using `flock`'s built-in support:
   - `TryRLockContext()` for shared/read locks (using cached chart)
   - `TryLockContext()` for exclusive/write locks (refresh/download)

2. **Shared locks allow concurrent reads** - multiple processes can use the same cached chart simultaneously

3. **Exclusive locks for refresh operations** - only one process can delete + re-download at a time

4. **Simplified lock lifecycle** - Locks are released immediately after download completes. This is safe because:
   - The `tempDir` cleanup is deferred until after helm operations complete in `withPreparedCharts()`
   - Charts won't be deleted mid-operation since the temp directory persists for the entire helm lifecycle

5. **Callback-based deduplication within a process** - The key fix for preventing redundant downloads:
   - `acquireChartLock()` accepts an optional `skipRefreshCheck` callback
   - Before deleting a cached chart for refresh, the callback checks the in-memory cache
   - If in-memory cache is populated (another worker downloaded it this run) → use cached, don't delete
   - If in-memory cache is empty (chart from a previous run) → respect `needsRefresh` flag

   This correctly handles both scenarios:
   - **Within-process**: Multiple releases with same chart → only one download
   - **Cross-run**: Floating tags with `--skip-refresh=false` → re-downloads as expected

6. **Removed the hardcoded 60s refresh marker timeout entirely** - lock-based synchronization provides proper coordination

**Why release locks immediately?**

Holding locks for the entire helm operation caused deadlocks when multiple releases shared the same OCI chart:
- Worker 1 acquires lock, downloads chart, waits for PrepareCharts to finish
- Worker 2 tries to acquire same lock, blocks
- PrepareCharts waits for Worker 2 → deadlock

**Test coverage:**
- Added `TestOCIChartSharedExclusiveLocks` verifying reader-writer lock behavior
- Added `TestOCIChartDoubleCheckLocking` verifying cache deduplication
