### PR TITLE
fix #1095

### LINKED ISSUE #1095: diffArgs passed to `helm list` when running `helmfile apply` with false `installed` conditions
### Operating system

Ubuntu 22.04.3 LTS

### Helmfile Version

0.158.0

### Helm Version

3.13.1

### Bug description

When running the command `helmfile apply` with a helmfile containing release(s) with `installed` conditions as false, if `helmDefault.diffArgs` is set, helmfile pass the diffArgs values to the `helm list` command.

### Example helmfile.yaml

```yaml
helmDefaults:
  diffArgs:
   - "--three-way-merge"

repositories:
  - name: deliveryhero 
    url: https://charts.deliveryhero.io/
      
releases: 
  - name: wiremock
    chart: deliveryhero/wiremock
    installed: false
```

### Error message you've seen (if any)

```txt
Listing releases matching ^wiremock$
in ./helmfile.yaml: command "/home/linuxbrew/.linuxbrew/bin/helm" exited with non-zero status:

PATH:
  /home/linuxbrew/.linuxbrew/bin/helm

ARGS:
  0: helm (4 bytes)
  1: list (4 bytes)
  2: --filter (8 bytes)
  3: ^wiremock$ (10 bytes)
  4: --uninstalling (14 bytes)
  5: --deployed (10 bytes)
  6: --failed (8 bytes)
  7: --pending (9 bytes)
  8: --three-way-merge (17 bytes)

ERROR:
  exit status 1

EXIT STATUS
  1

STDERR:
  Error: unknown flag: --three-way-merge

COMBINED OUTPUT:
  Error: unknown flag: --three-way-merge
```

### Steps to reproduce

See Bug description and exemple helmfile.yaml

### Working Helmfile Version

N/A

### Relevant discussion

_No response_

### PR DESCRIPTION
**Pull request by yxxhero**

### CODE REVIEW

File: pkg/argparser/args.go [hunk 1]
```diff
@@ -86,23 +81,10 @@ func analyzeArgs(am *argMap, args string) {
...
-
-	if len(state.HelmDefaults.Args) > 0 {
-		analyzeArgs(argsMap, strings.Join(state.HelmDefaults.Args, " "))
-	}
-
-	if len(state.HelmDefaults.DiffArgs) > 0 && opts != nil && opts.WithDiffArgs {
-		analyzeArgs(argsMap, strings.Join(state.HelmDefaults.DiffArgs, " "))
-	}
-
+	analyzeArgs(argsMap, args)
```
Comment (mumoshu) [inline pkg/argparser/args.go:86]: Where did the analyzeArgs call for `state.HelmDefaults.Args` go now?

Comment (mumoshu) [reply pkg/argparser/args.go:86]: Ah okay so you moved the entire GetArgs to pkg/app/app.go now? (But why?!

Comment (yxxhero) [reply pkg/argparser/args.go:86]: for solving import cycle issues. Make the `argparser` package more clean.

Comment (yxxhero) [reply pkg/argparser/args.go:86]: @mumoshu

File: pkg/app/app.go [hunk 2]
```diff
@@ -2223,3 +2213,23 @@ func (a *App) CleanCacheDir(c CacheConfigProvider) error {
...
+
+	if len(state.HelmDefaults.Args) > 0 {
+		stateArgs = argparser.CollectArgs(strings.Join(state.HelmDefaults.Args, " "))
+	}
+	arrArr := []string{}
+
+	arrArr = append(arrArr, baseArgs...)
+	arrArr = append(arrArr, stateArgs...)
+
+	state.HelmDefaults.Args = arrArr
```
Comment (xiaomudk) [inline pkg/app/app.go:2232]: It can be simplified:
```
state.HelmDefaults.Args = append(baseArgs, stateArgs...)
```

File: pkg/argparser/args.go (hunk 1 above)
Comment (xiaomudk) [reply pkg/argparser/args.go:86]: I think this is a good direction, argparser decouples the business logic.

**Review by xiaomudk — APPROVED** [review]
