### PR TITLE
fix: skip cache refresh for shared cache paths to prevent race conditions

### LINKED ISSUE #2387: Cache is refreshed while used in multi-process scenario
### Operating system

Ubuntu 24.04 LTS

### Helmfile Version

v1.2.3, and built from source

### Helm Version

v4.1.0

### Bug description

We are using `helmfile` as a plugin for ArgoCD. As such,w e often have multiple processes of `helmfile template` running in parallel.

When two of these processes use the same dependency, it can happen that the dependency downloaded in the cache is deleted by one process, while the other is using it to render its chart.
These leads to `Error: path "~/.cache/helmfile/envoyproxy/gateway-helm/1.6.2/gateway-helm" not found` like errors.

They appear since 1.1.7 introduced cached, and this wasn't fixed by the improvements of 1.2.2.
As it's a race condition, it's not always easy to reproduce, and I've only been able to reproduce it with OCI chart dependencies.

Using `--skip-refresh` could have been a fix for OCI charts which are downloaded by `helmfile` itself, but it's also preventing `helm` to properly download other dependencies.

### Example helmfile.yaml

```yaml
repositories:
  - name: envoyproxy
    url: docker.io/envoyproxy
    oci: true

releases:
  - name: envoy-gateway
    namespace: envoy-gateway-system
    createNamespace: true
    chart: envoyproxy/gateway-helm
    version: 1.6.2
```

### Error message you've seen (if any)

`Error: path "~/.cache/helmfile/envoyproxy/gateway-helm/1.6.2/gateway-helm" not found`

### Steps to reproduce

Run `helmfile template` on this helmfile from two distinct terminals at the same time. Multiple tries may be necessary for the error to pop up

### Working Helmfile Version

1.1.6

### Relevant discussion

_No response_

### PR DESCRIPTION
**Pull request by yxxhero**
## Summary

Fixes #2387 - Cache is refreshed while used in multi-process scenario

When multiple `helmfile template` processes run in parallel (e.g., as ArgoCD plugin), they share the same OCI chart cache in `~/.cache/helmfile`. One process could delete and re-download (refresh) a cached chart while another process was still using it, causing `Error: path "~/.cache/helmfile/..." not found`.

## Changes

- Added `isSharedCachePath()` helper function to detect if a chart path is within the shared cache directory
- Modified `acquireChartLock()` to skip refresh operations for charts in the shared cache
- Skipped deletion of corrupted charts in shared cache (logs warning instead)
- Added tests for `isSharedCachePath()` function

## Behavior

For charts in the shared cache (`~/.cache/helmfile`):
- If chart exists and is valid → use cached version
- If refresh is requested → skip deletion, use cached version
- If chart is corrupted → log warning, download to new location (don't delete)

For charts in process-specific temp directories:
- Behavior unchanged - refresh works as before

## Usage Note

Users who want to force a refresh of cached charts should run:
```bash
helmfile cache cleanup
```

This will clear the shared cache before running helmfile commands.

## Testing

- All existing OCI chart lock tests pass
- Added new tests for `isSharedCachePath()` function

### CODE REVIEW

**Comment by yxxhero** [comment]
@aditmeno PTAL

File: pkg/state/state.go [hunk 1]
```diff
@@ -4655,12 +4681,18 @@ func (st *HelmState) acquireChartLock(chartPath string, opts ChartPrepareOptions
...
 		} else {
 			// Directory exists but invalid (no Chart.yaml) - corrupted cache
-			st.logger.Debugf("Chart directory at %s is corrupted: %v, will re-download", chartPath, err)
-			if err := os.RemoveAll(chartPath); err != nil {
-				result.Release(st.logger)
-				return nil, fmt.Errorf("failed to remove corrupted chart directory: %w", err)
+			// Skip deletion for shared cache paths to prevent race conditions
+			if st.isSharedCachePath(chartPath) {
+				st.logger.Warnf("Chart directory at %s is corrupted but in shared cache, skipping deletion (use 'helmfile cache cleanup' to remove)", chartPath)
+				result.action = chartActionDownload
```
Comment (aditmeno) [inline pkg/state/state.go]: **Critical: Corrupted cache download into existing directory will likely fail or produce bad state**

When a corrupted directory is detected in the shared cache, this skips `os.RemoveAll` (correct for race-condition safety) but then sets `result.action = chartActionDownload`. After `acquireChartLock` returns, the caller `getOCIChart()` calls:

```go
helm.ChartPull(qualifiedChartName, chartPath, flags...)
helm.ChartExport(qualifiedChartName, chartPath)
```

This attempts to download into `chartPath` which is the **still-existing corrupted directory**. Depending on what `helm chart pull/export` does with an existing non-empty directory, this could:
- Fail outright
- Produce a partially valid chart with leftover corrupted files
- Silently succeed (overwriting files) but leave stale artifacts

**Recommendation:** Return an error telling the user to run `helmfile cache cleanup` instead. This is the safest option since we can't safely clean up the corrupted directory without risking the race condition this PR is trying to fix:

```go
if st.isSharedCachePath(chartPath) {
    result.Release(st.logger)
    return nil, fmt.Errorf("chart directory at %s is corrupted; cannot safely remove from shared cache while other processes may be running. Please run 'helmfile cache cleanup' to clear the cache", chartPath)
}
```

Alternatively, download to a temp location and atomically rename (more robust, but more complex).

File: pkg/state/state.go [hunk 2]
```diff
@@ -4646,6 +4664,14 @@ func (st *HelmState) acquireChartLock(chartPath string, opts ChartPrepareOptions
 				st.logger.Debugf("Skipping refresh for chart at %s (another worker already cached)", result.cachedPath)
 				return result, nil
 			}
+			// Skip refresh for shared cache paths to prevent race conditions when multiple
+			// processes are using the same cached chart. Use `helmfile cache cleanup` to force refresh.
+			if st.isSharedCachePath(chartPath) {
+				st.logger.Debugf("Skipping refresh for chart at %s (shared cache, another process may be using it)", chartPath)
```
Comment (aditmeno) [inline pkg/state/state.go]: **Important: Refresh skip should be logged at Info/Warn level, not Debug**

This silently changes the default behavior: refresh is now **always skipped** for any chart in the shared cache, even when `--skip-refresh` is NOT set. This means if a user publishes chart v1.2.3 to their OCI registry, deletes it, and re-publishes a different v1.2.3, helmfile will never pick up the new version without manual `helmfile cache cleanup`.

This is a valid tradeoff for multi-process safety, but it should be logged at `Infof` or `Warnf` level so users understand why their charts aren't refreshing. The current `Debugf` is invisible in normal usage.

```go
st.logger.Infof("Skipping refresh for chart at %s (shared cache, another process may be using it; run 'helmfile cache cleanup' to force refresh)", chartPath)
```

File: pkg/state/oci_chart_lock_test.go [hunk 3]
```diff
@@ -485,3 +489,70 @@ func TestOCIChartDoubleCheckLocking(t *testing.T) {
 		require.NoError(t, err, "chart should exist in cache")
 	})
 }
+
+// TestIsSharedCachePath tests the isSharedCachePath function to ensure it correctly
+// identifies paths within the shared cache directory.
+func TestIsSharedCachePath(t *testing.T) {
```
Comment (aditmeno) [inline pkg/state/oci_chart_lock_test.go:495]: **Important: Missing integration tests for the actual `acquireChartLock` behavioral changes**

The tests here only cover the `isSharedCachePath()` helper (a simple path-prefix check). The actual behavioral changes in `acquireChartLock` that fix the bug have **zero test coverage**:

1. **No test** that `acquireChartLock` returns `chartActionUseCached` (instead of `chartActionRefresh`) when the chart is valid, in the shared cache, and `needsRefresh=true`
2. **No test** that `os.RemoveAll` is NOT called when a corrupted cache is in the shared cache
3. **No test** simulating the multi-process scenario where one process is reading while another attempts refresh

The existing `TestOCIChartDoubleCheckLocking` test pattern could be extended to cover the shared-cache skip logic. For example, you could create a `HelmState` with a test filesystem where `chartPath` is under a temp directory set via `HELMFILE_CACHE_HOME`, then call `acquireChartLock` directly and assert:
- A valid chart in shared cache with `needsRefresh=true` → returns `chartActionUseCached`
- A corrupted chart in shared cache → returns an error (per the fix above)
- A valid chart in a non-shared path with `needsRefresh=true` → returns `chartActionRefresh` (existing behavior preserved)

File: pkg/state/oci_chart_lock_test.go [hunk 4]
```diff
@@ -485,3 +489,70 @@ func TestOCIChartDoubleCheckLocking(t *testing.T) {
...
+
+		// Test path that has shared cache dir as a prefix but not as the actual parent
+		// e.g., /home/user/.cache/helmfile-other/path should not match
+		sharedCacheDir := remote.CacheDir()
+		nonSubpath := sharedCacheDir + "-other/chart"
+		require.False(t, st.isSharedCachePath(nonSubpath), "path with shared cache as prefix but not subdirectory should return false")
+	})
+}
+
+func createTestLogger(t *testing.T) *zap.SugaredLogger {
```
Comment (aditmeno) [inline pkg/state/oci_chart_lock_test.go:633]: **Minor: `createTestLogger` should call `t.Helper()`**

Adding `t.Helper()` improves test failure output by reporting the caller's line number instead of the helper's:

```go
func createTestLogger(t *testing.T) *zap.SugaredLogger {
	t.Helper()
	logger, err := zap.NewDevelopment()
	require.NoError(t, err)
	return logger.Sugar()
}
```

**Comment by yxxhero** [comment]
@aditmeno please review this.

**Comment by aditmeno** [comment]
> @aditmeno please review this.

PR is almost ready, we just need an integration test for acquireChartLock changes to catch regressions which could creep in the future and after that LGTM

**Comment by yxxhero** [comment]
> > @aditmeno please review this.
> 
> PR is almost ready, we just need an integration test for acquireChartLock changes to catch regressions which could creep in the future and after that LGTM

tests added. @aditmeno

**Comment by yxxhero** [comment]
@aditmeno ping
