### PR TITLE
Use gopkg.in/yaml.v2 for Helmfile v0.x

### LINKED ISSUE #435: `.Release.Labels` are not available within values templates
### Operating system

macOS Monterey Version 12.5

### Helmfile Version

0.147.0

### Helm Version

3.10.1

### Bug description

Since 0.147.0 it seems like `.Release.Labels` are no longer available to use within values templates.
Same example works fine with previous releases. 

### Example helmfile.yaml

helmfile.yaml:
```
repositories:
  - name: jenkinsci
    url: https://charts.jenkins.io
 
templates:
  jenkins: &jenkins
    name: jenkins{{`{{.Release.Labels.jenkinsInstance}}`}}
    chart: jenkinsci/jenkins
    version: 4.1.16
    labels:
      group: jenkins
      privateRegistry: 123456789.dkr.ecr.us-west-1.amazonaws.com
    namespace: jenkins{{`{{.Release.Labels.jenkinsInstance}}`}}
    values:
      - jenkins.yaml.gotmpl

releases:
  - labels:
      jenkinsInstance: "1"
      zone: us-west-1b
      branch: master
      jobsTags: ""
    <<: *jenkins
```

jenkins.yaml.gotmpl:
```
agent:
  image: '{{ .Release.Labels.privateRegistry }}/jenkins-agent'
```

### Error message you've seen (if any)

in ./helmfile.yaml: failed to render values files "jenkins.yaml.gotmpl": failed to render [jenkins.yaml.gotmpl], because of template: stringTemplate:2:21: executing "stringTemplate" at <.Release.Labels.privateRegistry>: map has no entry for key "privateRegistry"

### Steps to reproduce

helmfile -f ./helmfile.yaml -l name=jenkins1 template

### Working Helmfile Version

0.146.0

### Relevant discussion

_No response_

### PR DESCRIPTION
**Pull request by mumoshu**
This should fix #435 for Helmfile v0.x releases since the next v0.150.0.
We introduce a new envvar to opt-in to the new YAML library, so that you can give it a shot before upgrading your Helmfile to v1. The same envvar can be used to opt-out of the new YAML library after you upgrade to Helmfile v1, giving you a more flexible migration story.

Signed-off-by: Yusuke Kuoka <ykuoka@gmail.com>

### CODE REVIEW

File: pkg/yaml/yaml.go [hunk 1]
```diff
@@ -66,11 +62,10 @@ func NewDecoder(data []byte, strict bool) func(interface{}) error {
 }
 
 func Marshal(v interface{}) ([]byte, error) {
-	if GoccyGoYaml {
+	if runtime.GoccyGoYaml {
 		var b bytes.Buffer
 		yamlEncoder := yaml.NewEncoder(
 			&b,
-			yaml.IndentSequence(true),
```
Comment (yxxhero) [inline pkg/yaml/yaml.go:73]: why do remove this option?

Comment (mumoshu) [reply pkg/yaml/yaml.go:73]: It turned out that this changed how Helmfile formatted YAML. The previous behavior with gopkg.in/yaml.v2 seems to correspond to goccy/go-yaml WITHOUT the IndentSequence option.

**Comment by mumoshu** [comment]
@yxxhero FYI, it seems like goccy/go-yaml is more strict when parsing `{{ ... }}` at the dict value position:

```
TEST: happypath - simple rollout of httpbin chart
INFO: Diffing test/integration/test-cases/happypath/input/happypath.yaml
in test/integration/test-cases/happypath/input/happypath.yaml: failed to read happypath.yaml: reading document at index 1: [28:20] unexpected mapping key
      25 |     chart: incubator/raw
      26 |     version: 0.2.3
      27 |     values:
    > 28 |       - mysecret: {{ .Environment.Values.mysecret }}
                              ^
      29 |       - values.yaml
      30 | 
      31 |   - name: helmx
      32 |     
FAIL: unexpected exit code returned by helmfile diff
```

I'm going to update `- mysecret: {{ .Environment.Values.mysecret }}` to `- mysecret: "{{ .Environment.Values.mysecret }}"` so that it's considered a valid YAML both by yaml.v2 and goccy/go-yaml.
Probably we might better document about the change in the v1 proposal too?

**Comment by mumoshu** [comment]
@yxxhero NVM. Apparently, it is due to that v1 mode requires .gotmpl ext for helmfile.yaml to enable the templating feature. We might need to rename every integration test input.yaml to input.yaml.gotmpl or come up with another way to make the integration test suite runnable for both helmfile v0 and v1 builds...

**Comment by yxxhero** [comment]
@mumoshu I agreed with you so much.

**Comment by yxxhero** [comment]
> @yxxhero FYI, it seems like goccy/go-yaml is more strict when parsing `{{ ... }}` at the dict value position:
> 
> ```
> TEST: happypath - simple rollout of httpbin chart
> INFO: Diffing test/integration/test-cases/happypath/input/happypath.yaml
> in test/integration/test-cases/happypath/input/happypath.yaml: failed to read happypath.yaml: reading document at index 1: [28:20] unexpected mapping key
>       25 |     chart: incubator/raw
>       26 |     version: 0.2.3
>       27 |     values:
>     > 28 |       - mysecret: {{ .Environment.Values.mysecret }}
>                               ^
>       29 |       - values.yaml
>       30 | 
>       31 |   - name: helmx
>       32 |     
> FAIL: unexpected exit code returned by helmfile diff
> ```
> 
> I'm going to update `- mysecret: {{ .Environment.Values.mysecret }}` to `- mysecret: "{{ .Environment.Values.mysecret }}"` so that it's considered a valid YAML both by yaml.v2 and goccy/go-yaml. Probably we might better document about the change in the v1 proposal too?

it's more conform to a standard of yaml spec. right? @mumoshu

**Comment by mumoshu** [comment]
@yxxhero Right. And it seems like every yaml implementation (yaml.v2, yaml.v3, and goccy/go-yaml) seems to fail if we tried to parse that. The failure was due to that I missed .gotmpl ext for helmfile v1 integration test.

**Comment by yxxhero** [comment]
@mumoshu yeah. you are right. we should update the ext of integration test files.

File: .github/workflows/ci.yaml [hunk 2]
```diff
@@ -71,23 +72,34 @@ jobs:
...
            plugin-diff-version: 3.6.0
            extra-helmfile-flags:
+           v1mode:
+         # Helmfile v1
+         - helm-version: v3.10.3
+           kustomize-version: v4.5.7
+           plugin-secrets-version: 4.0.0
+           plugin-diff-version: 3.6.0
+           extra-helmfile-flags:
+           v1mode: "true"
```
Comment (mumoshu) [inline .github/workflows/ci.yaml:94]: @yxxhero We now run the integration test suite for the v1 mode once per build, with the representative versions of helmfile dependencies, so that we won't break any v1 functionality until we finally stop maintaining v0.

File: .github/workflows/ci.yaml [hunk 3]
```diff
@@ -131,6 +143,7 @@ jobs:
         HELMFILE_HELM3: 1
         TERM: xterm
         EXTRA_HELMFILE_FLAGS: ${{ matrix.extra-helmfile-flags }}
+        HELMFILE_V1MODE: ${{ matrix.v1mode }}
```
Comment (mumoshu) [inline .github/workflows/ci.yaml:146]: FYI, `HELMFILE_V1MODE` is defined in pkg/runtime/runtime.go

File: pkg/app/app_template_test.go [hunk 4]
```diff
@@ -309,20 +309,21 @@ releases:
...
 	}
 
 	check := func(t *testing.T, tc testcase) {
 		t.Helper()
 
+		v := runtime.GoccyGoYaml
+		runtime.GoccyGoYaml = tc.goccyGoYaml
+		t.Cleanup(func() {
+			runtime.GoccyGoYaml = v
+		})
```
Comment (mumoshu) [inline pkg/app/app_template_test.go:325]: This is an idiom I used widely across many test sources to ensure we modify the GoccyGoYaml runtime variable only while running the (sub-)test.

File: pkg/app/app_template_test.go [hunk 5]
```diff
@@ -381,8 +382,9 @@ releases:
 		})
 	}
 
-	t.Run("fail due to known field", func(t *testing.T) {
+	t.Run("fail due to unknown field with goccy/go-yaml", func(t *testing.T) {
```
Comment (mumoshu) [inline pkg/app/app_template_test.go:385]: You might also see this idiom, the same test is run `with goccy/goyaml` and `with yaml.v2`, so that we are sure that we don't break anything while migrating to goccy/goyaml or helmfile v1.

File: pkg/runtime/runtime.go [hunk 6]
```diff
@@ -34,4 +44,14 @@ func init() {
 	default:
 		V1Mode, _ = strconv.ParseBool(v1Mode)
 	}
+
+	// You can switch the YAML library at runtime via an envvar:
+	switch os.Getenv(envvar.GoccyGoYaml) {
```
Comment (mumoshu) [inline pkg/runtime/runtime.go:49]: Although goccy/go-yaml is the default for v1, you can opt in/out in both v0 and v1, by setting this envvar.

File: pkg/state/release.go [hunk 7]
```diff
@@ -107,13 +108,18 @@ func (r ReleaseSpec) ExecuteTemplateExpressions(renderer *tmpl.FileRenderer) (*R
 					return nil, fmt.Errorf("failed executing template expressions in release \"%s\".values[%d] = \"%v\": %v", r.Name, i, string(serialized), err)
 				}
 
-				var deserialized map[interface{}]interface{}
+				var deserialized map[string]interface{}
```
Comment (mumoshu) [inline pkg/state/release.go:111]: yaml.v2 deserializes nested yaml dict to `map[interface{}]interface{}` while yaml.v3 and goccy/go-yaml serializes it to `map[string]interface{}`.
My original design was to ensure any nested dict is deserialized to the latter, by calling `maputil.CastKeysToStrings`

File: pkg/state/release.go [hunk 8]
```diff
@@ -130,6 +136,12 @@ func (r ReleaseSpec) ExecuteTemplateExpressions(renderer *tmpl.FileRenderer) (*R
 				return nil, fmt.Errorf("failed executing template expressions in release \"%s\".values[%d] = \"%s\": %v", r.Name, i, ts, err)
 			}
 			result.Values[i] = s.String()
+		case map[interface{}]interface{}:
```
Comment (mumoshu) [inline pkg/state/release.go:139]: https://github.com/helmfile/helmfile/pull/609/files#r1058925709

File: pkg/state/state_exec_tmpl_test.go [hunk 9]
```diff
@@ -121,7 +121,7 @@ func TestHelmState_executeTemplates(t *testing.T) {
 				Verify:    nil,
 				Name:      "app",
 				Namespace: "dev",
-				Values:    []interface{}{map[interface{}]interface{}{"key": "app-val0"}},
+				Values:    []interface{}{map[string]interface{}{"key": "app-val0"}},
```
Comment (mumoshu) [inline pkg/state/state_exec_tmpl_test.go:124]: https://github.com/helmfile/helmfile/pull/609/files#r1058925709

File: pkg/tmpl/context_funcs.go [hunk 10]
```diff
@@ -286,11 +287,17 @@ func ToYaml(v interface{}) (string, error) {
...
 
 func FromYaml(str string) (Values, error) {
-	m := Values{}
+	m := map[string]interface{}{}
 
 	if err := yaml.Unmarshal([]byte(str), &m); err != nil {
 		return nil, fmt.Errorf("%s, offending yaml: %s", err, str)
 	}
+
+	m, err := maputil.CastKeysToStrings(m)
```
Comment (mumoshu) [inline pkg/tmpl/context_funcs.go:296]: https://github.com/helmfile/helmfile/pull/609/files#r1058925709

This is especially important here because this function is supposed to be used like `fromYaml | toJson` within helmfile templates. Go's `json` pkg which powers `toJson` is unable to serialize `map[interface{}]interface{}` deserialized by yaml.v2. This CastKeysToStrings call normalizes it so that both yaml.v2 and goccy/go-yaml implementation of FromYaml is compatible with ToJson.

File: test/e2e/template/helmfile/snapshot_test.go [hunk 11]
```diff
@@ -57,6 +58,18 @@ func (f fakeInit) Force() bool {
 }
 
 func TestHelmfileTemplateWithBuildCommand(t *testing.T) {
+	t.Run("with goccy/go-yaml", func(t *testing.T) {
```
Comment (mumoshu) [inline test/e2e/template/helmfile/snapshot_test.go:61]: We now run all the snapshot tests for both goccy/go-yaml and yaml.v2

File: test/e2e/template/helmfile/snapshot_test.go [hunk 12]
```diff
@@ -200,6 +213,15 @@ func TestHelmfileTemplateWithBuildCommand(t *testing.T) {
 				}
 			}
 
+			tmpDir := t.TempDir()
+			// HELM_CACHE_HOME contains downloaded chart archives
+			helmCacheHome := filepath.Join(tmpDir, "helm_cache")
```
Comment (mumoshu) [inline test/e2e/template/helmfile/snapshot_test.go:218]: I had to give clean HELM_CACHE_HOME and HELM_CONFIG_HOME to every snapshot test case to make it not affected by the previous tests.

File: test/e2e/template/helmfile/testdata/snapshot/pr_560/output.yaml [hunk 13]
```diff
@@ -1,103 +1,5 @@
...
-remote> host: github.com
-remote> dir: /helmfile/helmfile.git
-remote> file: test/e2e/template/helmfile/testdata/snapshot/pr_560/secrets.yaml
-remote> home: /home/runner/.cache/helmfile
-remote> getter dest: values/https_github_com_helmfile_helmfile_git.ref=main
-remote> cached dir: /home/runner/.cache/helmfile/values/https_github_com_helmfile_helmfile_git.ref=main
-skipping missing secrets file matching "git::https://github.com/helmfile/helmfile.git@test/e2e/template/helmfile/testdata/snapshot/pr_560/secrets.yaml?ref=main"
 Templating release=foo, chart=../../charts/raw-0.1.0
-exec: helm template foo ../../charts/raw-0.1.0 --values /tmp/helmfile/foo-values-d459bc67c --debug
-helm> install.go:192: [debug] Original chart version: ""
```
Comment (mumoshu) [inline test/e2e/template/helmfile/testdata/snapshot/pr_560/output.yaml:86]: I had to disable debug logging for this test case because running it with yaml.v2 resulted in adding an extra `helm>` line here due to an unknown reason.
It looked harmless but hard to solve so I just disabled the debug log to make it stable.

File: test/e2e/template/helmfile/testdata/snapshot/release_template_inheritance/input.yaml [hunk 14]
```diff
@@ -12,7 +12,7 @@ templates:
     values:
     - template1: template1
     valuesTemplate:
-    - template1Label: "{{` '{{ .Release.Labels.template1 }}' `}}"
```
Comment (mumoshu) [inline test/e2e/template/helmfile/testdata/snapshot/release_template_inheritance/input.yaml:15]: I'm not completely sure, but goccy/go-yaml seemed to translate single quotes enclosed in double quotes to triple single quotes, which resulted in this test case failing.
You don't need the single quotes anyway to write a valid helmfile yaml for this configuration so I just omitted it.

File: test/e2e/template/helmfile/testdata/snapshot/release_template_inheritance/output.yaml [hunk 15]
```diff
@@ -33,13 +30,4 @@ data:
   inheritedBaseLabel: base
   template2: template2
   template2Label: template2
-  templates:
```
Comment (mumoshu) [inline test/e2e/template/helmfile/testdata/snapshot/release_template_inheritance/output.yaml:36]: yaml.v2 encoded this in the flow style but we are not interested in a specific yaml library to encode the same go map to a yaml dict in flow style or non-flow style. I just removed this key out of values to make the output look the same between yaml.v2 and goccy/go-yaml. See input.yaml for the change.

File: test/integration/test-cases/chart-needs.sh [hunk 16]
```diff
@@ -2,6 +2,14 @@ if [[ helm_major_version -eq 3 ]]; then
   chart_need_case_input_dir="${cases_dir}/chart-needs/input"
   chart_need_case_output_dir="${cases_dir}/chart-needs/output"
 
+  config_file="helmfile.yaml"
+  if [[ ${HELMFILE_V1MODE} = true ]]; then
+    pushd "${chart_need_case_input_dir}"
+    mv "${config_file}" "${config_file}.gotmpl"
+    config_file="${config_file}.gotmpl"
+    popd
+  fi
```
Comment (mumoshu) [inline test/integration/test-cases/chart-needs.sh:11]: This is a new idiom I used in all the integration test runner script to rename helmfile.yaml to helmfile.yaml.gotmpl only when it's run with v1 mode.

**Comment by mumoshu** [comment]
@yxxhero DCO is failing due to perhaps a few commits missed signoffs but I'm too lazy to fix it. It would be great if we could handle it by using the squash-and-merge option and including the signoff line in the squashed commit.

**Comment by yxxhero** [comment]
@mumoshu why `test/integration/test-cases/yaml-overwrite/input/issue.657.yaml.gotmpl` be renamed?

**Comment by mumoshu** [comment]
@yxxhero That's because it's supposed work only with goccy/go-yamlm and therefore helmfile v1, which requires .gotmpl. Remember that we now run the integration test suite against both helmfile v0 and v1!

**Comment by yxxhero** [comment]
> @yxxhero That's because it's supposed work only with goccy/go-yamlm and therefore helmfile v1, which requires .gotmpl. Remember that we now run the integration test suite against both helmfile v0 and v1, and that we run the yaml-overwrite test only for v1!

got.

**Review by yxxhero — APPROVED** [review]

**Comment by mumoshu** [comment]
@yxxhero Thanks for your review! Let's see how this works in the wild.
