### PR TITLE
Fix set flag are ignored when used in conjunction with jsonPatches

### LINKED ISSUE #853: Values set with --set flag are ignored when used in conjunction with jsonPatches
### Operating system

Fedora 37

### Helmfile Version

0.153.1

### Helm Version

v3.11.3

### Bug description

When jsonPatches are used in a helmfile, values overwritten with --set flag are ignored.
Let's take this helmfile.yaml as an example:
```yaml
releases:
- name: foo
  chart: oci://registry-1.docker.io/bitnamicharts/nginx
  version: 14.1.0
```
By default the replica count is 1:
```
$ helmfile template | grep replicas
Pulling registry-1.docker.io/bitnamicharts/nginx:14.1.0
Templating release=foo, chart=/tmp/chartify3659108862/foo
  replicas: 1
```
Let's say we'd like to increase the replicas:
```
$ helmfile template --set replicaCount=3 | grep replicas
Pulling registry-1.docker.io/bitnamicharts/nginx:14.1.0
Templating release=foo, chart=/tmp/chartify3653282249/foo
  replicas: 3
```
So far so good. Let's now assume that we want to change the deployment strategy with jsonPatches. Must be noted that there are much simpler ways of doing it, this is just for the sake of reproducing the behaviour:
```yaml
releases:
- name: foo
  chart: oci://registry-1.docker.io/bitnamicharts/nginx
  version: 14.1.0
  jsonPatches:
    - target:
        group: apps
        version: v1
        kind: Deployment
        name: foo-nginx
      patch:
      - path: "/spec/strategy/type"
        op: replace
        value: Recreate
```
Now values set with --set flag are ignored:
```
$ helmfile template --set replicaCount=3 | grep replicas
Pulling registry-1.docker.io/bitnamicharts/nginx:14.1.0
Templating release=foo, chart=/tmp/chartify2208595413/foo
  replicas: 1
```

### Example helmfile.yaml

```yaml
releases:
- name: foo
  chart: oci://registry-1.docker.io/bitnamicharts/nginx
  version: 14.1.0
  jsonPatches:
    - target:
        group: apps
        version: v1
        kind: Deployment
        name: foo-nginx
      patch:
      - path: "/spec/strategy/type"
        op: replace
        value: Recreate
```

### Error message you've seen (if any)

None

### Steps to reproduce

helmfile template --set replicaCount=3 --debug

### Working Helmfile Version

N/A

### Relevant discussion

_No response_

### PR DESCRIPTION
**Pull request by xiaomudk**
fix #853

### CODE REVIEW

File: test/integration/test-cases/chartify.sh [hunk 1]
```diff
@@ -0,0 +1,27 @@
...
+if [[ ${HELMFILE_V1MODE} = true ]]; then
+  pushd "${chart_need_case_input_dir}"
+  mv "${config_file}" "${config_file}.gotmpl"
+  config_file="${config_file}.gotmpl"
+  popd
+fi
+
+chartify_tmp=$(mktemp -d)
+chartify_template_reverse=${chart_needs_tmp}/chartify.template.log
+
```
Comment (yxxhero) [inline test/integration/test-cases/chartify.sh:14]: chart_needs_tmp?

**Review by yxxhero — APPROVED** [review]
